// ==UserScript==
// @name         bili-subtitle
// @namespace    https://github.com/ymt200120
// @version      1.0.1
// @description  弹性提取 Bilibili CC / AI 字幕：自动尝试多条获取路径，失败时给出精确诊断。零配置、不读取 Cookie。
// @description:en  Resilient Bilibili CC & AI subtitle extraction with automatic fallback strategies and precise diagnostics. Zero-config, never touches cookies.
// @author       ymt200120
// @homepageURL  https://github.com/ymt200120/bili-subtitle
// @supportURL   https://github.com/ymt200120/bili-subtitle/issues
// @downloadURL  https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @updateURL    https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @match        https://www.bilibili.com/video/*
// @match        https://www.bilibili.com/list/*
// @noframes
// @grant        GM_xmlhttpRequest
// @grant        GM_setClipboard
// @connect      api.bilibili.com
// @connect      aisubtitle.hdslb.com
// @connect      subtitle.bilibili.com
// @connect      hdslb.com
// @run-at       document-end
// @license      MIT
// ==/UserScript==

/*
 * bili-subtitle v1.0.1 - https://github.com/ymt200120/bili-subtitle
 * This file is generated by `npm run build`; edit files under src/ instead.
 */
(function () {
'use strict';

const BS = {};

BS.VERSION = '1.0.1';
BS.TAG = '[bili-subtitle]';

;(function () {
/*
 * Logging with a unified prefix and URL sanitization.
 *
 * Short-lived signed query parameters (auth_key, tokens, signatures)
 * must never appear in logs, and cookies are never read or logged.
 */

const SENSITIVE_PARAMS =
  /^(auth_key|authkey|token|sign|signature|w_rid|wts|session|sessdata|osa|credential|secret|access_key)$/i;

const SENSITIVE_PARAM_HINT =
  /^(auth|token|sign|w_|session|osa|credential|secret|access)/i;

function maskValue(value) {
  if (!value) return '***';
  if (value.length <= 4) return '***';
  return value.slice(0, 2) + '***' + value.slice(-2);
}

function sanitizeQueryValue(key, value) {
  if (SENSITIVE_PARAMS.test(key)) return '***';
  if (SENSITIVE_PARAM_HINT.test(key) && value.length >= 12) return '***';
  if (/^[0-9a-f]{16,}$/i.test(value)) return '***';
  return value;
}

function sanitizePath(path) {
  return path.replace(
    /[0-9a-f]{24,}/gi,
    (m) => m.slice(0, 6) + '***'
  );
}

function sanitizeUrl(rawUrl) {
  const url = String(rawUrl || '');
  const qIndex = url.indexOf('?');
  if (qIndex < 0) return sanitizePath(url);

  const base = sanitizePath(url.slice(0, qIndex));
  const query = url.slice(qIndex + 1);

  const masked = query
    .split('&')
    .map((pair) => {
      const eq = pair.indexOf('=');
      if (eq < 0) return pair;
      const key = pair.slice(0, eq);
      const value = pair.slice(eq + 1);
      return `${key}=${sanitizeQueryValue(key, value)}`;
    })
    .join('&');

  return `${base}?${masked}`;
}

function log(...args) {
  console.log(BS.TAG, ...args);
}

function warn(...args) {
  console.warn(BS.TAG, ...args);
}

function errorLog(...args) {
  console.error(BS.TAG, ...args);
}

BS.log = log;
BS.warn = warn;
BS.errorLog = errorLog;
BS.sanitizeUrl = sanitizeUrl;

})();
;(function () {
/*
 * Core data model + track scoring/selection.
 */

function makeVideoContext({ bvid, aid, cid, page, pageCount, title }) {
  return {
    bvid: String(bvid || ''),
    aid: Number(aid) || 0,
    cid: Number(cid) || 0,
    page: Number(page) || 1,
    pageCount: Number(pageCount) || 1,
    title: String(title || '')
  };
}

function makeTrack({ id, lan, lanDoc, url, source, aiType, aiStatus }) {
  return {
    id: id == null ? '' : String(id),
    lan: String(lan || ''),
    lanDoc: String(lanDoc || lan || ''),
    url: BS.normalizeSubtitleUrl(url),
    source: String(source || ''),
    aiType: aiType == null ? null : aiType,
    aiStatus: aiStatus == null ? null : aiStatus
  };
}

function normalizeSubtitleUrl(url) {
  const u = String(url || '');
  if (!u) return '';
  if (u.startsWith('//')) return 'https:' + u;
  if (u.startsWith('http://')) return 'https://' + u.slice(7);
  return u;
}

/*
 * Higher score = better default pick. ai-zh is the usual want;
 * human CC zh beats machine zh; everything else is a fallback.
 */
function languageScore(track) {
  const lan = String(track.lan || '').toLowerCase();
  const doc = String(track.lanDoc || '').toLowerCase();

  if (lan === 'ai-zh') return 100;
  if (lan.startsWith('ai-')) return 80;

  if (lan === 'zh-cn' || lan === 'zh-hans' || lan === 'zh') return 95;
  if (lan.startsWith('zh')) return 90;

  if (doc.includes('中文') || doc.includes('汉语')) return 92;

  if (lan.startsWith('en')) return 60;
  return 10;
}

function compareTracks(a, b) {
  return languageScore(b) - languageScore(a);
}

function sortTracks(tracks) {
  return tracks.slice().sort(compareTracks);
}

function mergeTracks(lists) {
  const seen = new Set();
  const out = [];
  for (const list of lists) {
    for (const t of list || []) {
      if (!t || !t.url) continue;
      const key = `${t.lan}|${t.url}`;
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(t);
    }
  }
  return sortTracks(out);
}

BS.makeVideoContext = makeVideoContext;
BS.makeTrack = makeTrack;
BS.normalizeSubtitleUrl = normalizeSubtitleUrl;
BS.languageScore = languageScore;
BS.mergeTracks = mergeTracks;
BS.sortTracks = sortTracks;

})();
;(function () {
/*
 * Video URL parsing for www.bilibili.com SPA routes.
 *
 * Supported: /video/BVxxxxxxxxxx (optionally ?p=N) and /list/BVxxxxxxxxxx?p=N.
 * Host is validated (www.bilibili.com); pure string logic so it also runs
 * in the vm test sandbox.
 */

const BV_URL_RE = /^(?:https?:)?\/\/(?:www\.)?bilibili\.com\/(?:video|list)\/(BV[0-9A-Za-z]+)/;
const P_RE = /[?&]p=(\d+)/;

function parseVideoUrl(href) {
  const raw = String(href || '');
  if (!raw) return null;

  const url = raw.split('#', 1)[0];
  const match = url.match(BV_URL_RE);
  if (!match) return null;

  let page = 1;
  const pMatch = url.match(P_RE);
  if (pMatch) {
    const n = Number(pMatch[1]);
    if (Number.isFinite(n) && n >= 1) page = Math.floor(n);
  }

  return { bvid: match[1], page };
}

function isVideoPage(href) {
  return parseVideoUrl(href) !== null;
}

BS.parseVideoUrl = parseVideoUrl;
BS.isVideoPage = isVideoPage;

})();
;(function () {
/*
 * Subtitle body parsing and cue normalization.
 *
 * Bilibili subtitle JSON: { "body": [ { "from": 0.0, "to": 1.2, "content": "..." } ] }
 * Long AI tracks can arrive segmented; sort and drop exact duplicates.
 */

function parseCue(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const content = typeof raw.content === 'string' ? raw.content.trim() : '';
  if (!content) return null;
  const from = Number(raw.from);
  const to = Number(raw.to);
  return {
    from: Number.isFinite(from) && from >= 0 ? from : 0,
    to: Number.isFinite(to) && to >= 0 ? to : 0,
    content
  };
}

function sortAndDedupe(cues) {
  cues.sort((a, b) => a.from - b.from || a.to - b.to);
  const out = [];
  for (const cue of cues) {
    const prev = out[out.length - 1];
    if (
      prev &&
      prev.content === cue.content &&
      Math.abs(prev.from - cue.from) < 0.001 &&
      Math.abs(prev.to - cue.to) < 0.001
    ) {
      continue;
    }
    out.push(cue);
  }
  return out;
}

function parseSubtitleJson(data) {
  const body = data && Array.isArray(data.body) ? data.body : [];
  const cues = [];
  for (const raw of body) {
    const cue = parseCue(raw);
    if (cue) cues.push(cue);
  }
  return sortAndDedupe(cues);
}

BS.parseSubtitleJson = parseSubtitleJson;
BS.sortAndDedupe = sortAndDedupe;

})();
;(function () {
/*
 * Exporters: plain text / timestamped text / SRT / JSON.
 */

function pad(n, width = 2) {
  return String(n).padStart(width, '0');
}

function fmtClock(sec, withMs = false) {
  sec = Math.max(0, Number(sec) || 0);
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec - Math.floor(sec)) * 1000);

  if (withMs) {
    return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms, 3)}`;
  }
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(s)}` : `${pad(m)}:${pad(s)}`;
}

function toPlainText(cues) {
  return cues.map((c) => c.content).join('\n');
}

function toTimestampedText(cues) {
  return cues.map((c) => `${fmtClock(c.from)}  ${c.content}`).join('\n');
}

function toSrt(cues) {
  return cues
    .map(
      (c, i) =>
        `${i + 1}\n${fmtClock(c.from, true)} --> ${fmtClock(c.to, true)}\n${c.content}\n`
    )
    .join('\n');
}

function toJson(video, track, cues) {
  return JSON.stringify(
    {
      video: {
        bvid: video.bvid,
        aid: video.aid,
        cid: video.cid,
        page: video.page,
        title: video.title
      },
      track: {
        lan: track.lan,
        lanDoc: track.lanDoc,
        source: track.source
      },
      generator: `bili-subtitle ${BS.VERSION}`,
      body: cues.map((c) => ({ from: c.from, to: c.to, content: c.content }))
    },
    null,
    2
  );
}

function safeName(name) {
  return String(name || 'bilibili-subtitle')
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 100);
}

BS.exporters = { fmtClock, toPlainText, toTimestampedText, toSrt, toJson, safeName };

})();
;(function () {
/*
 * Resolver diagnostics. One Step per resolver attempt, rendered as
 * ✓ / ✗ / ○ lines for the UI and console. Endpoints are sanitized
 * before being stored or displayed.
 */

const OK = 'ok';
const FAIL = 'fail';
const SKIP = 'skip';

function createDiagnostics() {
  const steps = [];

  function add(step) {
    steps.push({
      resolver: step.resolver || '',
      status: step.status || FAIL,
      detail: step.detail || '',
      httpStatus: step.httpStatus || 0,
      endpoint: step.endpoint ? BS.sanitizeUrl(step.endpoint) : '',
      ms: step.ms || 0
    });
  }

  function render() {
    return steps.map((s) => {
      const mark = s.status === OK ? '✓' : s.status === SKIP ? '○' : '✗';
      const parts = [`${mark} ${s.resolver}`];
      if (s.detail) parts.push(s.detail);
      if (s.httpStatus) parts.push(`HTTP ${s.httpStatus}`);
      if (s.endpoint) parts.push(s.endpoint);
      if (s.ms) parts.push(`${s.ms}ms`);
      return parts.join(' · ');
    });
  }

  return { steps, add, render };
}

BS.diagnostics = { createDiagnostics, OK, FAIL, SKIP };

})();
;(function () {
/*
 * Minimal protobuf wire-format decoder for /x/v2/subtitle/web/view.
 *
 * Protocol basis (see docs/PROTOCOL.md):
 *   top-level field 1 (length-delimited) = data message
 *   data field 3 (repeated, length-delimited) = subtitle track
 *     track field 1 (varint)            = id
 *     track field 2 (string)            = id_str
 *     track field 3 (string)            = lan        e.g. "ai-zh" / "zh-Hans"
 *     track field 4 (string)            = lan_doc    display name
 *     track field 5 (string)            = subtitle_url
 *     track field 8 (string)            = label (optional)
 *
 * Unknown fields are skipped, never assumed away. The decoder supports
 * wire types 0 (varint), 1 (64-bit), 2 (length-delimited) and 5 (32-bit);
 * wire types 3/4 (deprecated groups) abort parsing. Numbers are decoded
 * with Number (safe here: ids and lengths are far below 2^53).
 */

function readVarint(bytes, offset) {
  let value = 0;
  let shift = 0;
  let pos = offset;
  for (;;) {
    if (pos >= bytes.length) {
      throw new Error(`unterminated varint at ${offset}`);
    }
    const byte = bytes[pos++];
    if (shift < 28) {
      value += (byte & 0x7f) * Math.pow(2, shift);
    } else {
      value = value * Math.pow(2, 7) + (byte & 0x7f);
    }
    if ((byte & 0x80) === 0) return { value, offset: pos };
    shift += 7;
    if (shift > 63) {
      throw new Error(`varint too long at ${offset}`);
    }
  }
}

function decodeMessage(bytes) {
  const fields = [];
  let offset = 0;
  while (offset < bytes.length) {
    const key = readVarint(bytes, offset);
    offset = key.offset;
    const no = key.value / 8 | 0;
    const wt = key.value % 8;
    if (no <= 0) throw new Error(`invalid field number ${no}`);

    if (wt === 0) {
      const value = readVarint(bytes, offset);
      offset = value.offset;
      fields.push({ no, wt, value: value.value });
    } else if (wt === 1) {
      const end = offset + 8;
      if (end > bytes.length) throw new Error('truncated 64-bit field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else if (wt === 2) {
      const len = readVarint(bytes, offset);
      offset = len.offset;
      const end = offset + len.value;
      if (end > bytes.length) throw new Error('truncated length-delimited field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else if (wt === 5) {
      const end = offset + 4;
      if (end > bytes.length) throw new Error('truncated 32-bit field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else {
      throw new Error(`unsupported wire type ${wt}`);
    }
  }
  return fields;
}

const textDecoder = new TextDecoder('utf-8', { fatal: false });

function getString(fields, no) {
  const field = fields.find((f) => f.no === no && f.wt === 2 && f.bytes);
  return field ? textDecoder.decode(field.bytes) : '';
}

function getVarint(fields, no) {
  const field = fields.find((f) => f.no === no && f.wt === 0);
  return field ? field.value : 0;
}

function toTracks(dataFields) {
  const tracks = [];
  for (const field of dataFields) {
    if (field.no !== 3 || field.wt !== 2 || !field.bytes) continue;
    let inner;
    try {
      inner = decodeMessage(field.bytes);
    } catch (e) {
      BS.warn('protobuf: 跳过损坏的轨道字段', e.message);
      continue;
    }
    const lan = getString(inner, 3);
    const url = getString(inner, 5);
    if (!lan || !url) continue;
    tracks.push({
      id: getVarint(inner, 1) || 0,
      idStr: getString(inner, 2),
      lan,
      lanDoc: getString(inner, 4),
      url,
      label: getString(inner, 8)
    });
  }
  return tracks;
}

function decodeWebViewTracks(buffer) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  const top = decodeMessage(bytes);
  const dataField = top.find((f) => f.no === 1 && f.wt === 2 && f.bytes);
  if (!dataField) {
    return { empty: true, tracks: [] };
  }
  const dataFields = decodeMessage(dataField.bytes);
  const tracks = toTracks(dataFields);
  return { empty: tracks.length === 0, tracks };
}

BS.protobuf = { decodeMessage, decodeWebViewTracks };

})();
;(function () {
/*
 * Network layer. Prefers GM_xmlhttpRequest (bypasses CORS, carries
 * bilibili login cookies automatically for api.bilibili.com) and falls
 * back to page-context fetch with credentials when GM is unavailable.
 *
 * Errors carry structured info (phase / httpStatus / sanitized endpoint)
 * for the diagnostics UI. Cookie values are never read or logged.
 */

function gmRequest(options) {
  return new Promise((resolve, reject) => {
    GM_xmlhttpRequest({
      method: 'GET',
      timeout: 15000,
      headers: {
        Accept: 'application/json,text/plain,*/*',
        Referer: 'https://www.bilibili.com/'
      },
      ...options,
      onload: (r) => resolve(r),
      onerror: () => reject(new Error('network error')),
      ontimeout: () => reject(new Error('timeout'))
    });
  });
}

function pageFetch(url, { responseType } = {}) {
  const consume =
    responseType === 'arraybuffer'
      ? (r) => r.arrayBuffer().then((buffer) => ({
          status: r.status,
          response: buffer,
          contentType: r.headers.get('content-type') || ''
        }))
      : (r) => r.text().then((text) => ({
          status: r.status,
          response: text,
          contentType: r.headers.get('content-type') || ''
        }));

  return fetch(url, {
    method: 'GET',
    credentials: 'include'
  }).then(consume);
}

class NetError extends Error {
  constructor(message, { status, endpoint, phase, body } = {}) {
    super(message);
    this.name = 'NetError';
    this.status = status || 0;
    this.endpoint = endpoint ? BS.sanitizeUrl(endpoint) : '';
    this.phase = phase || '';
    this.body = body ? String(body).slice(0, 200) : '';
  }
}

async function request(url, { phase = '', responseType = 'text', timeout = 15000 } = {}) {
  let status;
  let response;
  let contentType;

  if (typeof GM_xmlhttpRequest === 'function') {
    try {
      const r = await gmRequest({ url, timeout, responseType });
      status = r.status;
      contentType = r.responseHeaders || '';
      response = responseType === 'arraybuffer' ? r.response : r.responseText;
    } catch (e) {
      throw new NetError(`网络错误或超时：${e.message}`, {
        endpoint: url,
        phase
      });
    }
  } else {
    try {
      const r = await pageFetch(url, { responseType });
      status = r.status;
      contentType = r.contentType;
      response = r.response;
    } catch (e) {
      throw new NetError(`网络错误：${e.message}`, {
        endpoint: url,
        phase
      });
    }
  }

  if (status < 200 || status >= 300) {
    let body = '';
    try {
      if (responseType === 'arraybuffer') {
        body = new TextDecoder().decode(new Uint8Array(response)).slice(0, 120);
      } else {
        body = String(response).slice(0, 120);
      }
    } catch (_) { /* ignore */ }
    throw new NetError(`HTTP ${status}`, { status, endpoint: url, phase, body });
  }

  return { status, response, contentType };
}

async function getJson(url, opts = {}) {
  const { response } = await request(url, { ...opts, responseType: 'text' });
  try {
    return JSON.parse(response);
  } catch (e) {
    throw new NetError('返回内容不是 JSON', {
      endpoint: url,
      phase: opts.phase || 'parse-json',
      body: String(response)
    });
  }
}

async function getBinary(url, opts = {}) {
  const { response } = await request(url, { ...opts, responseType: 'arraybuffer' });
  return response instanceof ArrayBuffer ? response : new Uint8Array(response).buffer;
}

BS.net = { request, getJson, getBinary, NetError };

})();
;(function () {
/*
 * SPA navigation detection for www.bilibili.com (no polling).
 *
 * Bilibili routes through history.pushState/replaceState; wrapping them
 * plus popstate/hashchange covers video-to-video jumps, multi-page
 * switches and player rebuilds without touching MutationObserver.
 */

function installSpaHooks(onNavigate) {
  const wrapped = [];

  function wrapMethod(obj, name) {
    if (!obj || typeof obj[name] !== 'function') return;
    const original = obj[name];
    try {
      obj[name] = function (...args) {
        const result = original.apply(this, args);
        onNavigate();
        return result;
      };
      wrapped.push([obj, name, original]);
    } catch (e) {
      BS.warn('SPA hook 失败', name, e && e.message);
    }
  }

  wrapMethod(window.history, 'pushState');
  wrapMethod(window.history, 'replaceState');

  window.addEventListener('popstate', onNavigate);
  window.addEventListener('hashchange', onNavigate);

  return function uninstall() {
    for (const [obj, name, original] of wrapped) {
      try {
        obj[name] = original;
      } catch (_) { /* ignore */ }
    }
    window.removeEventListener('popstate', onNavigate);
    window.removeEventListener('hashchange', onNavigate);
  };
}

BS.installSpaHooks = installSpaHooks;

})();
;(function () {
/*
 * VideoContext resolver: URL -> { bvid, aid, cid, page, pageCount, title }.
 *
 * Prefers the page-embedded __INITIAL_STATE__ (zero extra requests),
 * falls back to the public view API. In SPA state the embedded data can
 * lag behind navigation, so a bvid mismatch sends us to the API.
 */

const VIEW_API = 'https://api.bilibili.com/x/web-interface/view?bvid=';

function pickPage(pages, wanted) {
  if (!Array.isArray(pages) || pages.length === 0) return null;
  const found = pages.find((x) => Number(x && x.page) === wanted);
  if (found) return found;
  // A missing page number means the embedded data does not describe this
  // URL's part; falling back to pages[0] would silently extract the wrong
  // cid (wrong subtitles). Only the default P1 may use the first page.
  if (!wanted || wanted === 1) return pages[0];
  return null;
}

function contextFromVideoData(videoData, page) {
  if (!videoData || !videoData.bvid) return null;
  const pages = Array.isArray(videoData.pages) ? videoData.pages : [];
  const selected = pickPage(pages, page);
  if (!selected && pages.length > 1) return null;
  const cid = Number((selected && selected.cid) || videoData.cid) || 0;
  if (!cid) return null;
  const base = String(videoData.title || '');
  const multi = pages.length > 1 && selected && selected.part;
  return BS.makeVideoContext({
    bvid: videoData.bvid,
    aid: videoData.aid,
    cid,
    page: Number((selected && selected.page) || page || 1),
    pageCount: pages.length || 1,
    title: multi ? `${base} P${selected.page || page} ${selected.part}` : base
  });
}

async function resolve(env) {
  const parsed = BS.parseVideoUrl(env.href);
  if (!parsed) {
    throw new Error('当前页面不是 B 站视频页（未识别到 BV 号）');
  }

  const inline = contextFromVideoData(
    env.initialState && env.initialState.videoData,
    parsed.page
  );
  if (inline && inline.bvid === parsed.bvid) {
    return inline;
  }

  const data = await env.net.getJson(VIEW_API + encodeURIComponent(parsed.bvid), {
    phase: 'video-context'
  });
  if (!data || data.code !== 0 || !data.data) {
    throw new Error(`视频信息获取失败：code ${data && data.code} ${data && data.message}`);
  }
  const ctx = contextFromVideoData(data.data, parsed.page);
  if (!ctx) throw new Error('视频信息中没有可用的 cid');
  return ctx;
}

BS.resolvers = BS.resolvers || {};
BS.resolvers.videoContext = { name: 'video-context', resolve };

})();
;(function () {
/*
 * Strategy A - Legacy JSON subtitle list.
 *
 * GET /x/player/v2?bvid=&cid=  ->  data.subtitle.subtitles[]
 *
 * Verified behavior: anonymous requests return code 0 with an EMPTY
 * subtitles array for AI-only videos, so an empty list is reported as
 * "ok but empty (possibly login-gated)", not as a hard failure.
 */

async function discover(ctx, env) {
  const url =
    'https://api.bilibili.com/x/player/v2' +
    `?bvid=${encodeURIComponent(ctx.bvid)}` +
    `&cid=${encodeURIComponent(ctx.cid)}`;

  const data = await env.net.getJson(url, { phase: 'legacy-json' });
  if (!data || typeof data.code !== 'number') {
    throw new Error('响应缺少 code 字段');
  }
  if (data.code !== 0) {
    throw new Error(`接口返回 code ${data.code}：${data.message || '未知错误'}`);
  }

  const subs = data.data && data.data.subtitle && data.data.subtitle.subtitles;
  if (!Array.isArray(subs) || subs.length === 0) {
    return { tracks: [], note: '字幕列表为空（AI 轨道通常需要登录）' };
  }

  const tracks = subs.map((s, i) =>
    BS.makeTrack({
      id: s.id != null ? s.id : i,
      lan: s.lan,
      lanDoc: s.lan_doc,
      url: s.subtitle_url,
      source: 'legacy',
      aiType: s.ai_type,
      aiStatus: s.ai_status
    })
  );

  return { tracks: tracks.filter((t) => t.url), note: `${tracks.length} 条轨道` };
}

BS.resolvers.legacy = { name: 'legacy-json', discover };

})();
;(function () {
/*
 * Strategy B - New web subtitle metadata API (protobuf).
 *
 * GET /x/v2/subtitle/web/view?oid=<cid>&pid=<aid>&type=1
 *     &context_ext={"video_type":1}&cur_production_type=0&playlist_switch=0
 *
 * Verified anonymously (2026-08): HTTP 200, application/octet-stream,
 * an empty protobuf data message when no tracks are visible (e.g. not
 * logged in). Invalid parameters return a JSON error instead, so the
 * response is sniffed before decoding. See docs/PROTOCOL.md.
 */

function buildUrl(ctx) {
  return (
    'https://api.bilibili.com/x/v2/subtitle/web/view' +
    `?oid=${encodeURIComponent(ctx.cid)}` +
    `&pid=${encodeURIComponent(ctx.aid)}` +
    '&type=1' +
    `&context_ext=${encodeURIComponent('{"video_type":1}')}` +
    '&cur_production_type=0' +
    '&playlist_switch=0'
  );
}

function looksLikeJson(bytes) {
  for (let i = 0; i < Math.min(bytes.length, 16); i++) {
    const b = bytes[i];
    if (b === 0x20 || b === 0x09 || b === 0x0a || b === 0x0d) continue;
    return b === 0x7b || b === 0x5b; // '{' or '['
  }
  return false;
}

async function discover(ctx, env) {
  const url = buildUrl(ctx);
  const buffer = await env.net.getBinary(url, { phase: 'web-view' });
  const bytes = new Uint8Array(buffer);

  if (looksLikeJson(bytes)) {
    let parsed = null;
    try {
      parsed = JSON.parse(new TextDecoder().decode(bytes));
    } catch (_) { /* fallthrough */ }
    if (parsed && parsed.code !== undefined && parsed.code !== 0) {
      throw new Error(`接口返回 code ${parsed.code}：${parsed.message || '未知错误'}`);
    }
    throw new Error('响应为 JSON 但无法识别');
  }

  const { empty, tracks } = BS.protobuf.decodeWebViewTracks(bytes);
  if (empty) {
    return { tracks: [], note: '接口可达但无轨道（未登录或该视频无 AI 字幕）' };
  }

  return {
    tracks: tracks.map((t) =>
      BS.makeTrack({
        id: t.idStr || t.id,
        lan: t.lan,
        lanDoc: t.lanDoc || t.label,
        url: t.url,
        source: 'web-view'
      })
    ),
    note: `${tracks.length} 条轨道`
  };
}

BS.resolvers.webView = { name: 'web-view', discover };

})();
;(function () {
/*
 * Strategy C (last resort) - Player resource capture.
 *
 * The player's own subtitle requests (aisubtitle.hdslb.com,
 * subtitle.bilibili.com, /bfs/subtitle/) show up as PerformanceResource
 * entries. Entries are captured event-driven via PerformanceObserver
 * (buffered: true), capped, and cleared on SPA navigation so a previous
 * video's URLs can never be reused for the current one.
 *
 * Candidates are validated by fetching; only URLs that parse into cues
 * are accepted. Ownership check is strict and unconditional: a captured
 * URL is only probed when it embeds the current cid, or (on single-page
 * videos, where the aid uniquely identifies the part) the current aid.
 * The resource buffer can hold subtitle URLs of *other* videos (playlist
 * prefetch, script re-injection replays), so URLs without ownership
 * evidence are never probed. This trades a rare fallback (id-less CC
 * URLs) for never showing another video's subtitles.
 */

const SUBTITLE_URL_RE =
  /aisubtitle\.hdslb\.com|subtitle\.bilibili\.com|\/bfs\/subtitle\//;
const MAX_ENTRIES = 50;
const MAX_PROBES = 8;

const capture = {
  entries: [],
  observer: null,

  remember(rawUrl) {
    if (!rawUrl || typeof rawUrl !== 'string') return;
    if (!SUBTITLE_URL_RE.test(rawUrl)) return;
    if (this.entries.some((e) => e.url === rawUrl)) return;
    this.entries.push({ url: rawUrl, time: Date.now() });
    if (this.entries.length > MAX_ENTRIES) {
      this.entries.splice(0, this.entries.length - MAX_ENTRIES);
    }
  },

  install() {
    if (typeof PerformanceObserver === 'undefined') return;
    try {
      const po = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) {
          this.remember(entry.name);
        }
      });
      po.observe({ type: 'resource', buffered: true });
      this.observer = po;
    } catch (e) {
      BS.warn('PerformanceObserver 不可用', e && e.message);
    }
    if (typeof performance !== 'undefined' && performance.getEntriesByType) {
      try {
        for (const entry of performance.getEntriesByType('resource')) {
          this.remember(entry.name);
        }
      } catch (_) { /* ignore */ }
    }
  },

  list() {
    return this.entries.slice().sort((a, b) => b.time - a.time);
  },

  reset() {
    this.entries = [];
  }
};

function matchesNumber(url, number) {
  if (!number) return false;
  return new RegExp(`(^|[^0-9])${number}([^0-9]|$)`).test(String(url));
}

/*
 * Ownership evidence: the URL embeds the current cid, or it embeds the
 * aid on a single-page video. Multi-page videos share one aid across all
 * parts, so an aid-only match could be another part's subtitles.
 */
function ownsUrl(url, ctx) {
  if (!url || !ctx) return false;
  if (matchesNumber(url, ctx.cid)) return true;
  const singlePage = !ctx.pageCount || Number(ctx.pageCount) <= 1;
  return singlePage && matchesNumber(url, ctx.aid);
}

async function probe(env, item) {
  const data = await env.net.getJson(item.url, { phase: 'player-resource' });
  const cues = BS.parseSubtitleJson(data);
  if (!cues.length) {
    throw new Error('字幕内容为空');
  }
  const track = BS.makeTrack({
    id: 'captured',
    lan: /ai_subtitle|aisubtitle/.test(item.url) ? 'ai-zh' : '',
    lanDoc: '播放器已加载字幕',
    url: item.url,
    source: 'player-resource'
  });
  track.cues = cues;
  return track;
}

async function discover(ctx, env) {
  const all = env.getEntries ? env.getEntries() : capture.list();
  const candidates = all.filter((e) => SUBTITLE_URL_RE.test(e.url));

  if (!candidates.length) {
    return {
      tracks: [],
      note: '尚无播放器字幕请求（可在播放器中打开 CC 字幕后重试）',
      soft: true
    };
  }

  const pool = candidates.filter((e) => ownsUrl(e.url, ctx));
  if (!pool.length) {
    return {
      tracks: [],
      note: `捕获到 ${candidates.length} 条字幕 URL，但与当前视频不匹配（已跳过，避免串用其他视频的字幕）`
    };
  }

  const tracks = [];
  for (const item of pool.slice(0, MAX_PROBES)) {
    try {
      tracks.push(await probe(env, item));
    } catch (e) {
      BS.log('捕获 URL 无效，跳过', BS.sanitizeUrl(item.url), e && e.message);
    }
  }

  if (!tracks.length) {
    return { tracks: [], note: '捕获的 URL 均无法读取（可能已过期）' };
  }
  return { tracks, note: `${tracks.length} 条可读取` };
}

BS.resolvers = BS.resolvers || {};
BS.resolvers.playerResource = { name: 'player-resource', discover, ownsUrl };
BS.resourceCapture = capture;

})();
;(function () {
/*
 * Subtitle resolver pipeline.
 *
 * Strategies run in order (legacy JSON -> protobuf web view -> player
 * resource capture). Each strategy discovers tracks and tries to load a
 * body; the first success wins. Signed subtitle URLs are never cached:
 * a 403/404 body fetch triggers one extra discovery round with fresh
 * metadata. Every attempt is recorded as a diagnostics step.
 *
 * env = { net, href, initialState, getEntries, onUpdate, onContext }
 * (all injectable so the whole pipeline runs under node:test with mocks)
 */

const EXPIRY_STATUS = [403, 404];

function isExpiryError(err) {
  return err && EXPIRY_STATUS.includes(err.status);
}

function now() {
  return Date.now();
}

async function loadBody(track, env, tried) {
  if (Array.isArray(track.cues) && track.cues.length) {
    return track.cues;
  }
  if (!track.url || tried.has(track.url)) {
    throw new Error('跳过（已尝试过或无地址）');
  }
  tried.add(track.url);

  const data = await env.net.getJson(track.url, { phase: 'body' });
  const cues = BS.parseSubtitleJson(data);
  if (!cues.length) throw new Error('字幕内容为空');
  return cues;
}

async function runStrategy(resolver, ctx, env, diag, tried) {
  const started = now();

  let result;
  try {
    result = await resolver.discover(ctx, env);
  } catch (e) {
    diag.add({
      resolver: resolver.name,
      status: BS.diagnostics.FAIL,
      detail: e.message,
      httpStatus: e.status,
      endpoint: e.endpoint,
      ms: now() - started
    });
    BS.warn(resolver.name, '失败', e);
    return { tracks: [], retryable: isExpiryError(e) };
  }

  const okDetail = result.note || `${result.tracks.length} 条轨道`;
  diag.add({
    resolver: resolver.name,
    status: result.soft ? BS.diagnostics.SKIP : BS.diagnostics.OK,
    detail: okDetail,
    ms: now() - started
  });

  if (!result.tracks.length) {
    return { tracks: [], retryable: false };
  }

  const candidates = BS.sortTracks(
    result.tracks.filter((t) => !tried.has(t.url))
  );

  let sawExpiry = false;
  for (const track of candidates) {
    if (Array.isArray(track.cues) && track.cues.length) {
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.OK,
        detail: `${track.cues.length} 条（播放器捕获验证）`,
        ms: 0
      });
      return { tracks: result.tracks, doc: { track, cues: track.cues } };
    }
    const bodyStarted = now();
    try {
      const cues = await loadBody(track, env, tried);
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.OK,
        detail: `${track.lanDoc || track.lan} · ${cues.length} 条`,
        ms: now() - bodyStarted
      });
      return { tracks: result.tracks, doc: { track, cues } };
    } catch (e) {
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.FAIL,
        detail: e.message,
        httpStatus: e.status,
        endpoint: e.endpoint,
        ms: now() - bodyStarted
      });
      if (isExpiryError(e)) {
        sawExpiry = true;
        BS.warn('字幕地址已过期，将重新获取 metadata', BS.sanitizeUrl(track.url));
      }
    }
  }

  return { tracks: result.tracks, retryable: sawExpiry };
}

function buildHints(diagSteps) {
  const okNote = (name) =>
    diagSteps.some(
      (s) =>
        s.resolver === name &&
        s.status === BS.diagnostics.OK &&
        s.detail &&
        !/条/.test(s.detail)
    );

  const notes = [];
  if (okNote('legacy-json') && okNote('web-view')) {
    notes.push('两个字幕接口都返回空轨道：AI 字幕通常需要登录 B 站后才能获取。');
  }
  notes.push('兜底提示：在播放器中打开「字幕 / CC」并选择 AI 字幕，让播放器实际加载一次，再点「重新提取」。');
  return notes;
}

async function extract(env) {
  const diag = BS.diagnostics.createDiagnostics();
  const tried = new Set();
  env.onUpdate && env.onUpdate('正在识别视频…');

  let ctx;
  try {
    ctx = await BS.resolvers.videoContext.resolve(env);
  } catch (e) {
    diag.add({
      resolver: 'video-context',
      status: BS.diagnostics.FAIL,
      detail: e.message
    });
    return { ok: false, error: e, tracks: [], diag };
  }
  diag.add({
    resolver: 'video-context',
    status: BS.diagnostics.OK,
    detail: `${ctx.bvid} · cid ${ctx.cid} · P${ctx.page}`
  });
  env.onContext && env.onContext(ctx);

  const strategies = [
    BS.resolvers.legacy,
    BS.resolvers.webView,
    BS.resolvers.playerResource
  ];

  let merged = [];
  let doc = null;
  let retryable = false;

  for (const strategy of strategies) {
    env.onUpdate && env.onUpdate(`正在尝试：${strategy.name}`);
    const r = await runStrategy(strategy, ctx, env, diag, tried);
    merged = BS.mergeTracks([merged, r.tracks]);
    if (r.doc) {
      doc = r.doc;
      break;
    }
    if (r.retryable) retryable = true;
  }

  if (!doc && retryable) {
    env.onUpdate && env.onUpdate('字幕地址已过期，正在重新获取…');
    for (const strategy of [BS.resolvers.legacy, BS.resolvers.webView]) {
      const r = await runStrategy(strategy, ctx, env, diag, tried);
      merged = BS.mergeTracks([merged, r.tracks]);
      if (r.doc) {
        doc = r.doc;
        break;
      }
    }
  }

  // Belt and suspenders: never offer a track we cannot prove belongs to
  // the current video. legacy/web-view URLs come from APIs queried with
  // the current cid/aid; player-resource URLs must pass the ownership
  // check or they are dropped from the track list entirely.
  merged = merged.filter(
    (t) =>
      !t ||
      t.source !== 'player-resource' ||
      BS.resolvers.playerResource.ownsUrl(t.url, ctx)
  );

  if (!doc) {
    const hints = buildHints(diag.steps);
    const error = new Error(
      ['未能提取到字幕', ...hints].filter(Boolean).join('\n')
    );
    error.hints = hints;
    return { ok: false, error, ctx, tracks: merged, diag };
  }

  return { ok: true, ctx, track: doc.track, cues: doc.cues, tracks: merged, diag };
}

async function loadTrackBody(track, env) {
  const started = now();
  const cues = await env.net.getJson(track.url, { phase: 'body' }).then((d) => {
    const parsed = BS.parseSubtitleJson(d);
    if (!parsed.length) throw new Error('字幕内容为空');
    return parsed;
  });
  BS.log('轨道加载完成', track.lanDoc || track.lan, `${cues.length} 条`, `${now() - started}ms`);
  return cues;
}

BS.pipeline = { extract, loadTrackBody };

})();
;(function () {
/*
 * Minimal UI: a "字幕" pill at the bottom-right and a small popover with
 * track list, export actions, preview and collapsed diagnostics.
 *
 * Dynamic content is set via textContent only (no HTML interpolation of
 * video titles or subtitle text). No settings page, no themes.
 */

const STYLE = `
#bs-pill {
  position: fixed; right: 20px; bottom: 84px; z-index: 2147483644;
  border: 0; border-radius: 999px; background: #fb7299; color: #fff;
  padding: 8px 14px; font-size: 13px; font-weight: 600; cursor: pointer;
  box-shadow: 0 4px 14px rgba(0,0,0,.25); font-family: inherit;
}
#bs-panel {
  position: fixed; right: 20px; bottom: 130px; z-index: 2147483645;
  width: min(400px, calc(100vw - 40px)); max-height: min(70vh, 560px);
  overflow: auto; background: #fff; color: #18191c; border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0,0,0,.3); font-size: 13px; line-height: 1.6;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif;
}
#bs-head {
  display: flex; align-items: center; gap: 8px; padding: 10px 12px;
  border-bottom: 1px solid #eee;
}
#bs-title { flex: 1; min-width: 0; font-weight: 700;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
#bs-close { border: 0; background: transparent; font-size: 18px;
  cursor: pointer; color: #888; line-height: 1; }
#bs-status { padding: 6px 12px; color: #666; font-size: 12px; }
#bs-msg { margin: 0 12px 8px; padding: 8px 10px; border-radius: 8px;
  background: #fdeef0; color: #b2303f; white-space: pre-wrap; }
#bs-controls { display: flex; flex-wrap: wrap; gap: 6px; padding: 0 12px 8px; }
#bs-count { padding: 0 12px 6px; color: #444; }
#bs-actions { display: flex; flex-wrap: wrap; gap: 6px; padding: 0 12px 8px; }
#bs-panel button, #bs-panel select {
  border: 1px solid #ddd; border-radius: 7px; background: #fff;
  padding: 5px 9px; cursor: pointer; color: #18191c; font-size: 12px; max-width: 100%;
}
#bs-panel button:hover { border-color: #fb7299; color: #fb7299; }
#bs-preview { margin: 0 12px 8px; padding: 8px 10px; background: #f7f8fa;
  border-radius: 8px; max-height: 180px; overflow: auto; white-space: pre-wrap;
  font: 12px/1.6 ui-monospace, Menlo, Consolas, monospace; }
#bs-diag-box { margin: 0 12px 10px; }
#bs-diag-box summary { cursor: pointer; color: #888; font-size: 12px; }
#bs-diag { margin: 6px 0 0; padding: 8px 10px; background: #f7f8fa;
  border-radius: 8px; white-space: pre-wrap; font: 11px/1.7 ui-monospace, Menlo, Consolas, monospace; }
`;

const TEMPLATE = `
<div id="bs-panel" hidden>
  <div id="bs-head">
    <span id="bs-title">bili-subtitle</span>
    <button id="bs-close" title="关闭">×</button>
  </div>
  <div id="bs-status">就绪</div>
  <div id="bs-msg" hidden></div>
  <div id="bs-controls">
    <button id="bs-extract">提取字幕</button>
    <select id="bs-tracks" hidden></select>
  </div>
  <div id="bs-count" hidden></div>
  <div id="bs-actions" hidden>
    <button data-act="copy">复制文本</button>
    <button data-act="copy-ts">带时间轴</button>
    <button data-act="txt">TXT</button>
    <button data-act="srt">SRT</button>
    <button data-act="json">JSON</button>
  </div>
  <pre id="bs-preview" hidden></pre>
  <details id="bs-diag-box" hidden>
    <summary>获取路径</summary>
    <pre id="bs-diag"></pre>
  </details>
</div>
`;

function createPanel(handlers) {
  const root = document.createElement('div');
  root.id = 'bs-root';

  const style = document.createElement('style');
  style.textContent = STYLE;
  root.appendChild(style);

  const pill = document.createElement('button');
  pill.id = 'bs-pill';
  pill.textContent = '字幕';
  root.appendChild(pill);

  root.insertAdjacentHTML('beforeend', TEMPLATE);
  document.body.appendChild(root);

  const $ = (id) => root.querySelector(`#${id}`);
  const panel = $('bs-panel');
  const title = $('bs-title');
  const status = $('bs-status');
  const msg = $('bs-msg');
  const extractBtn = $('bs-extract');
  const tracksSel = $('bs-tracks');
  const count = $('bs-count');
  const actions = $('bs-actions');
  const preview = $('bs-preview');
  const diagBox = $('bs-diag-box');
  const diagPre = $('bs-diag');

  let trackKeyOf = () => '';

  function open() {
    panel.hidden = false;
  }

  function close() {
    panel.hidden = true;
  }

  pill.addEventListener('click', () => {
    if (panel.hidden) {
      open();
      if (handlers.onOpen) handlers.onOpen();
    } else {
      close();
    }
  });

  $('bs-close').addEventListener('click', close);
  extractBtn.addEventListener('click', () => handlers.onExtract());

  tracksSel.addEventListener('change', () => {
    handlers.onTrackChange(tracksSel.value);
  });

  actions.addEventListener('click', (e) => {
    const act = e.target && e.target.dataset && e.target.dataset.act;
    if (act) handlers.onExport(act);
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') close();
  });

  const api = {
    open,
    close,

    setTitle(text) {
      title.textContent = text || 'bili-subtitle';
    },

    setStatus(text) {
      status.textContent = text || '';
    },

    setMessage(text) {
      if (text) {
        msg.textContent = text;
        msg.hidden = false;
      } else {
        msg.hidden = true;
      }
    },

    setBusy(busy) {
      extractBtn.disabled = !!busy;
      extractBtn.textContent = busy ? '提取中…' : '提取字幕';
    },

    setTracks(tracks, selectedKey) {
      tracksSel.innerHTML = '';
      trackKeyOf = (t) => `${t.source}|${t.lan}|${t.url}`;
      for (const t of tracks) {
        const opt = document.createElement('option');
        opt.value = trackKeyOf(t);
        const label = t.lanDoc || t.lan || '字幕';
        opt.textContent =
          t.source === 'player-resource'
            ? `${label}（播放器捕获）`
            : label;
        if (trackKeyOf(t) === selectedKey) opt.selected = true;
        tracksSel.appendChild(opt);
      }
      tracksSel.hidden = tracks.length < 2;
    },

    findTrack(tracks, key) {
      return tracks.find((t) => `${t.source}|${t.lan}|${t.url}` === key) || null;
    },

    setCues(cues, track) {
      count.textContent = `${cues.length} 条 · ${track.lanDoc || track.lan || '字幕'} · 来源 ${track.source}`;
      count.hidden = false;
      actions.hidden = false;
      const head = cues
        .slice(0, 15)
        .map((c) => BS.exporters.fmtClock(c.from) + '  ' + c.content)
        .join('\n');
      preview.textContent =
        cues.length > 15 ? head + '\n…' : head;
      preview.hidden = false;
      msg.hidden = true;
    },

    setDiag(lines) {
      if (!lines || !lines.length) return;
      diagPre.textContent = lines.join('\n');
      diagBox.hidden = false;
    },

    clearResult() {
      count.hidden = true;
      actions.hidden = true;
      preview.hidden = true;
      msg.hidden = true;
      tracksSel.innerHTML = '';
      tracksSel.hidden = true;
      diagPre.textContent = '';
      diagBox.hidden = true;
    }
  };

  return api;
}

BS.ui = { createPanel };

})();
;(function () {
/*
 * Entry point: state, UI wiring, export actions, SPA reset.
 */

function createAppState() {
  // gen: monotonic token. Every user action that starts an async flow
  // (extract, track load) or invalidates one (SPA navigation) bumps it;
  // a flow whose gen is no longer current must not touch state or panel.
  return { ctx: null, tracks: [], track: null, cues: [], gen: 0 };
}

function makeEnv(state, panel, isStale) {
  return {
    net: BS.net,
    href: location.href,
    initialState: typeof window.__INITIAL_STATE__ !== 'undefined'
      ? window.__INITIAL_STATE__
      : null,
    getEntries: () => BS.resourceCapture.list(),
    onUpdate: (text) => {
      if (!isStale || !isStale()) panel.setStatus(text);
    },
    onContext: (ctx) => {
      if (!isStale || !isStale()) panel.setTitle(ctx.title || ctx.bvid);
    }
  };
}

function copyText(text) {
  if (typeof GM_setClipboard === 'function') {
    GM_setClipboard(text, 'text');
    return Promise.resolve();
  }
  return navigator.clipboard.writeText(text);
}

function downloadText(text, filename, type = 'text/plain;charset=utf-8') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.documentElement.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

function baseName(state) {
  return BS.exporters.safeName(
    (state.ctx && state.ctx.title) || state.ctx.bvid || 'bilibili-subtitle'
  );
}

function applyResult(state, panel, result) {
  state.tracks = result.tracks || [];
  panel.setDiag(result.diag.render());

  if (!result.ok) {
    state.track = null;
    state.cues = [];
    panel.setMessage(result.error.message);
    panel.setStatus('提取失败，详见「获取路径」');
    BS.errorLog('提取失败');
    for (const line of result.diag.render()) BS.errorLog(line);
    return;
  }

  state.track = result.track;
  state.cues = result.cues;
  panel.setMessage('');
  panel.setTracks(state.tracks, `${result.track.source}|${result.track.lan}|${result.track.url}`);
  panel.setCues(result.cues, result.track);
  panel.setStatus('提取成功');
  BS.log(
    '提取成功',
    result.track.lanDoc || result.track.lan,
    `${result.cues.length} 条`,
    `来源 ${result.track.source}`
  );
}

async function onExtract(state, panel) {
  if (state.extracting) return;
  const gen = ++state.gen;
  state.extracting = true;
  panel.setBusy(true);
  panel.clearResult();
  panel.setMessage('');

  const stale = () => gen !== state.gen;
  try {
    const result = await BS.pipeline.extract(makeEnv(state, panel, stale));
    if (stale()) {
      BS.log('提取结果已过期（视频已切换），丢弃');
      return;
    }
    state.ctx = result.ctx || state.ctx;
    applyResult(state, panel, result);
  } catch (e) {
    if (stale()) {
      BS.log('提取错误已过期（视频已切换），丢弃');
      return;
    }
    panel.setMessage(e && e.message ? e.message : String(e));
    panel.setStatus('提取失败');
    BS.errorLog('未预期的错误', e);
  } finally {
    // A superseded run must not clear the busy flag of the run that owns
    // the current gen (the SPA hook already reset the flag when it bumped gen).
    if (!stale()) {
      state.extracting = false;
      panel.setBusy(false);
    }
  }
}

async function onTrackChange(state, panel, key) {
  const track = panel.findTrack(state.tracks, key);
  if (!track) return;
  const gen = ++state.gen;
  const stale = () => gen !== state.gen;
  panel.setStatus(`正在读取：${track.lanDoc || track.lan}…`);
  try {
    const cues = await BS.pipeline.loadTrackBody(track, makeEnv(state, panel, stale));
    if (stale()) {
      BS.log('轨道结果已过期，丢弃');
      return;
    }
    state.track = track;
    state.cues = cues;
    panel.setCues(cues, track);
    panel.setStatus('提取成功');
  } catch (e) {
    if (stale()) return;
    panel.setStatus('轨道读取失败');
    panel.setMessage(
      (e && e.status === 403) || (e && e.status === 404)
        ? '该字幕地址已过期，请点「提取字幕」重新获取。'
        : (e && e.message) || String(e)
    );
    BS.warn('轨道读取失败', BS.sanitizeUrl(track.url), e && e.message);
  }
}

function onExport(state, panel, act) {
  if (!state.cues || !state.cues.length || !state.track) {
    panel.setStatus('当前没有字幕，请先提取');
    return;
  }
  const { cues, track, ctx } = state;
  const base = baseName(state);
  const done = (what) => panel.setStatus(`${what}完成`);

  switch (act) {
    case 'copy':
      copyText(BS.exporters.toPlainText(cues)).then(
        () => done('复制'),
        () => panel.setStatus('复制失败')
      );
      break;
    case 'copy-ts':
      copyText(BS.exporters.toTimestampedText(cues)).then(
        () => done('复制'),
        () => panel.setStatus('复制失败')
      );
      break;
    case 'txt':
      downloadText(BS.exporters.toTimestampedText(cues), `${base}.txt`);
      done('TXT 下载');
      break;
    case 'srt':
      downloadText(
        BS.exporters.toSrt(cues),
        `${base}.srt`,
        'application/x-subrip;charset=utf-8'
      );
      done('SRT 下载');
      break;
    case 'json':
      downloadText(
        BS.exporters.toJson(ctx, track, cues),
        `${base}.json`,
        'application/json;charset=utf-8'
      );
      done('JSON 下载');
      break;
  }
}

function boot() {
  if (!document.body) return false;

  const state = createAppState();
  const panel = BS.ui.createPanel({
    onOpen: () => {
      if (!state.cues.length && !state.extracting) onExtract(state, panel);
    },
    onExtract: () => onExtract(state, panel),
    onTrackChange: (key) => onTrackChange(state, panel, key),
    onExport: (act) => onExport(state, panel, act)
  });

  BS.resourceCapture.install();

  BS.installSpaHooks(() => {
    // Invalidate any in-flight extract / track load for the previous
    // video; their results must never land on the new video's panel.
    state.gen++;
    BS.resourceCapture.reset();
    state.extracting = false;
    panel.setBusy(false);
    state.ctx = null;
    state.tracks = [];
    state.track = null;
    state.cues = [];
    panel.clearResult();
    panel.setTitle('bili-subtitle');
    panel.setStatus('已切换视频，点击「提取字幕」');
    BS.log('SPA 导航：状态已重置');
  });

  BS.log(`v${BS.VERSION} 已加载`);
  return true;
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot);
} else {
  boot();
}

})();
})();
