// ==UserScript==
// @name         Bilibili CC / AI Subtitle Extractor
// @name:zh-CN   Bilibili CC / AI 字幕提取器
// @namespace    https://github.com/ymt200120
// @version      1.0.3
// @description  Resilient Bilibili CC & AI subtitle extraction with automatic fallback strategies and precise diagnostics.
// @description:zh-CN  零配置提取 Bilibili CC / AI 字幕，自动尝试多条获取路径，失败时提供精确诊断。
// @author       ymt200120
// @homepageURL  https://github.com/ymt200120/bili-subtitle
// @supportURL   https://github.com/ymt200120/bili-subtitle/issues
// @downloadURL  https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @updateURL    https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @match        https://www.bilibili.com/video/*
// @match        https://www.bilibili.com/list/*
// @noframes
// @grant        GM_xmlhttpRequest
// @grant        GM_setClipboard
// @connect      api.bilibili.com
// @connect      aisubtitle.hdslb.com
// @connect      subtitle.bilibili.com
// @connect      hdslb.com
// @run-at       document-end
// @license      MIT
// ==/UserScript==

/*
 * bili-subtitle v1.0.3 - https://github.com/ymt200120/bili-subtitle
 * This file is generated by `npm run build`; edit files under src/ instead.
 */
(function () {
'use strict';

const BS = {};

BS.VERSION = '1.0.3';
BS.TAG = '[bili-subtitle]';

;(function () {
/*
 * Logging with a unified prefix and URL sanitization.
 *
 * Short-lived signed query parameters (auth_key, tokens, signatures)
 * must never appear in logs, and cookies are never read or logged.
 */

const SENSITIVE_PARAMS =
  /^(auth_key|authkey|token|sign|signature|w_rid|wts|session|sessdata|osa|credential|secret|access_key)$/i;

const SENSITIVE_PARAM_HINT =
  /^(auth|token|sign|w_|session|osa|credential|secret|access)/i;

function maskValue(value) {
  if (!value) return '***';
  if (value.length <= 4) return '***';
  return value.slice(0, 2) + '***' + value.slice(-2);
}

function sanitizeQueryValue(key, value) {
  if (SENSITIVE_PARAMS.test(key)) return '***';
  if (SENSITIVE_PARAM_HINT.test(key) && value.length >= 12) return '***';
  if (/^[0-9a-f]{16,}$/i.test(value)) return '***';
  return value;
}

function sanitizePath(path) {
  return path.replace(
    /[0-9a-f]{24,}/gi,
    (m) => m.slice(0, 6) + '***'
  );
}

function sanitizeUrl(rawUrl) {
  const url = String(rawUrl || '');
  const qIndex = url.indexOf('?');
  if (qIndex < 0) return sanitizePath(url);

  const base = sanitizePath(url.slice(0, qIndex));
  const query = url.slice(qIndex + 1);

  const masked = query
    .split('&')
    .map((pair) => {
      const eq = pair.indexOf('=');
      if (eq < 0) return pair;
      const key = pair.slice(0, eq);
      const value = pair.slice(eq + 1);
      return `${key}=${sanitizeQueryValue(key, value)}`;
    })
    .join('&');

  return `${base}?${masked}`;
}

function log(...args) {
  console.log(BS.TAG, ...args);
}

function warn(...args) {
  console.warn(BS.TAG, ...args);
}

function errorLog(...args) {
  console.error(BS.TAG, ...args);
}

BS.log = log;
BS.warn = warn;
BS.errorLog = errorLog;
BS.sanitizeUrl = sanitizeUrl;

})();
;(function () {
/*
 * Core data model + track scoring/selection.
 */

/*
 * Resolver trust levels. Availability (a resolver returned tracks) is
 * separate from authority (the tracks are provably bound to the current
 * video). Only winnable tracks may become the winner or enter the
 * selectable track list.
 *
 * SIGNED_METADATA: metadata requested through a WBI-signed endpoint.
 * CURRENT_VIDEO_METADATA: metadata requested with the current aid+cid in
 *   the query (the endpoint binds the request to the video).
 * CURRENT_PLAYER_RESOURCE: URL captured from the player's own request and
 *   proven to embed the current cid/aid (see player-resource.ownsUrl).
 * UNTRUSTED_LEGACY: unsigned /x/player/v2 — observed in the wild (risk
 *   control degradation) returning HTTP 200 with valid-looking subtitles
 *   that belong to a DIFFERENT video. Diagnostic only; never committable.
 */
const TRUST = {
  SIGNED: 'SIGNED_METADATA',
  CURRENT_VIDEO: 'CURRENT_VIDEO_METADATA',
  CURRENT_PLAYER: 'CURRENT_PLAYER_RESOURCE',
  UNTRUSTED_LEGACY: 'UNTRUSTED_LEGACY'
};

function isWinnableTrust(trust) {
  return (
    trust === TRUST.SIGNED ||
    trust === TRUST.CURRENT_VIDEO ||
    trust === TRUST.CURRENT_PLAYER
  );
}

function makeVideoContext({ bvid, aid, cid, page, pageCount, title }) {
  const bvidStr = String(bvid || '');
  const cidNum = Number(cid) || 0;
  return {
    bvid: bvidStr,
    aid: Number(aid) || 0,
    cid: cidNum,
    page: Number(page) || 1,
    pageCount: Number(pageCount) || 1,
    title: String(title || ''),
    // Stable identity of (video, part). Every track / result / document
    // must carry this to be committable for this context.
    contextKey: `${bvidStr}:${cidNum}`
  };
}

function makeTrack({ id, lan, lanDoc, url, source, aiType, aiStatus, contextKey, trust }) {
  return {
    id: id == null ? '' : String(id),
    lan: String(lan || ''),
    lanDoc: String(lanDoc || lan || ''),
    url: BS.normalizeSubtitleUrl(url),
    source: String(source || ''),
    aiType: aiType == null ? null : aiType,
    aiStatus: aiStatus == null ? null : aiStatus,
    contextKey: String(contextKey || ''),
    trust: String(trust || '')
  };
}

function normalizeSubtitleUrl(url) {
  const u = String(url || '');
  if (!u) return '';
  if (u.startsWith('//')) return 'https:' + u;
  if (u.startsWith('http://')) return 'https://' + u.slice(7);
  return u;
}

/*
 * Higher score = better default pick. ai-zh is the usual want;
 * human CC zh beats machine zh; everything else is a fallback.
 */
function languageScore(track) {
  const lan = String(track.lan || '').toLowerCase();
  const doc = String(track.lanDoc || '').toLowerCase();

  if (lan === 'ai-zh') return 100;
  if (lan.startsWith('ai-')) return 80;

  if (lan === 'zh-cn' || lan === 'zh-hans' || lan === 'zh') return 95;
  if (lan.startsWith('zh')) return 90;

  if (doc.includes('中文') || doc.includes('汉语')) return 92;

  if (lan.startsWith('en')) return 60;
  return 10;
}

function compareTracks(a, b) {
  return languageScore(b) - languageScore(a);
}

function sortTracks(tracks) {
  return tracks.slice().sort(compareTracks);
}

function mergeTracks(lists) {
  const seen = new Set();
  const out = [];
  for (const list of lists) {
    for (const t of list || []) {
      if (!t || !t.url) continue;
      const key = `${t.lan}|${t.url}`;
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(t);
    }
  }
  return sortTracks(out);
}

BS.makeVideoContext = makeVideoContext;
BS.makeTrack = makeTrack;
BS.trust = TRUST;
BS.isWinnableTrust = isWinnableTrust;
BS.normalizeSubtitleUrl = normalizeSubtitleUrl;
BS.languageScore = languageScore;
BS.mergeTracks = mergeTracks;
BS.sortTracks = sortTracks;

})();
;(function () {
/*
 * Video URL parsing for www.bilibili.com SPA routes.
 *
 * Supported: /video/BVxxxxxxxxxx (optionally ?p=N) and /list/BVxxxxxxxxxx?p=N.
 * Host is validated (www.bilibili.com); pure string logic so it also runs
 * in the vm test sandbox.
 */

const BV_URL_RE = /^(?:https?:)?\/\/(?:www\.)?bilibili\.com\/(?:video|list)\/(BV[0-9A-Za-z]+)/;
const P_RE = /[?&]p=(\d+)/;

function parseVideoUrl(href) {
  const raw = String(href || '');
  if (!raw) return null;

  const url = raw.split('#', 1)[0];
  const match = url.match(BV_URL_RE);
  if (!match) return null;

  let page = 1;
  const pMatch = url.match(P_RE);
  if (pMatch) {
    const n = Number(pMatch[1]);
    if (Number.isFinite(n) && n >= 1) page = Math.floor(n);
  }

  return { bvid: match[1], page };
}

function isVideoPage(href) {
  return parseVideoUrl(href) !== null;
}

BS.parseVideoUrl = parseVideoUrl;
BS.isVideoPage = isVideoPage;

})();
;(function () {
/*
 * Subtitle body parsing and cue normalization.
 *
 * Bilibili subtitle JSON: { "body": [ { "from": 0.0, "to": 1.2, "content": "..." } ] }
 * Long AI tracks can arrive segmented; sort and drop exact duplicates.
 */

function parseCue(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const content = typeof raw.content === 'string' ? raw.content.trim() : '';
  if (!content) return null;
  const from = Number(raw.from);
  const to = Number(raw.to);
  return {
    from: Number.isFinite(from) && from >= 0 ? from : 0,
    to: Number.isFinite(to) && to >= 0 ? to : 0,
    content
  };
}

function sortAndDedupe(cues) {
  cues.sort((a, b) => a.from - b.from || a.to - b.to);
  const out = [];
  for (const cue of cues) {
    const prev = out[out.length - 1];
    if (
      prev &&
      prev.content === cue.content &&
      Math.abs(prev.from - cue.from) < 0.001 &&
      Math.abs(prev.to - cue.to) < 0.001
    ) {
      continue;
    }
    out.push(cue);
  }
  return out;
}

function parseSubtitleJson(data) {
  const body = data && Array.isArray(data.body) ? data.body : [];
  const cues = [];
  for (const raw of body) {
    const cue = parseCue(raw);
    if (cue) cues.push(cue);
  }
  return sortAndDedupe(cues);
}

BS.parseSubtitleJson = parseSubtitleJson;
BS.sortAndDedupe = sortAndDedupe;

})();
;(function () {
/*
 * Exporters: plain text / timestamped text / SRT / JSON.
 */

function pad(n, width = 2) {
  return String(n).padStart(width, '0');
}

function fmtClock(sec, withMs = false) {
  sec = Math.max(0, Number(sec) || 0);
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec - Math.floor(sec)) * 1000);

  if (withMs) {
    return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms, 3)}`;
  }
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(s)}` : `${pad(m)}:${pad(s)}`;
}

function toPlainText(cues) {
  return cues.map((c) => c.content).join('\n');
}

function toTimestampedText(cues) {
  return cues.map((c) => `${fmtClock(c.from)}  ${c.content}`).join('\n');
}

function toSrt(cues) {
  return cues
    .map(
      (c, i) =>
        `${i + 1}\n${fmtClock(c.from, true)} --> ${fmtClock(c.to, true)}\n${c.content}\n`
    )
    .join('\n');
}

function toJson(video, track, cues) {
  return JSON.stringify(
    {
      video: {
        bvid: video.bvid,
        aid: video.aid,
        cid: video.cid,
        page: video.page,
        title: video.title
      },
      track: {
        lan: track.lan,
        lanDoc: track.lanDoc,
        source: track.source
      },
      generator: `bili-subtitle ${BS.VERSION}`,
      body: cues.map((c) => ({ from: c.from, to: c.to, content: c.content }))
    },
    null,
    2
  );
}

function safeName(name) {
  return String(name || 'bilibili-subtitle')
    .replace(/[\\/:*?"<>|]/g, '_')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 100);
}

BS.exporters = { fmtClock, toPlainText, toTimestampedText, toSrt, toJson, safeName };

})();
;(function () {
/*
 * Resolver diagnostics. One Step per resolver attempt, rendered as
 * ✓ / ✗ / ○ lines for the UI and console. Endpoints are sanitized
 * before being stored or displayed.
 *
 * Since v1.0.2 each extract run carries a runId, the resolved video
 * context and the final decision block, so a single copied diag block
 * identifies which resolver won and why the others were ignored.
 */

const OK = 'ok';
const FAIL = 'fail';
const SKIP = 'skip';

function createDiagnostics(opts = {}) {
  const steps = [];
  const meta = { runId: opts.runId || 0, context: null, decision: [] };

  function add(step) {
    steps.push({
      resolver: step.resolver || '',
      status: step.status || FAIL,
      detail: step.detail || '',
      httpStatus: step.httpStatus || 0,
      endpoint: step.endpoint ? BS.sanitizeUrl(step.endpoint) : '',
      trust: step.trust || '',
      ms: step.ms || 0
    });
  }

  function setContext(ctx) {
    meta.context = ctx || null;
  }

  function setDecision(lines) {
    meta.decision = Array.isArray(lines) ? lines.slice() : [];
  }

  function renderStep(s) {
    const mark = s.status === OK ? '✓' : s.status === SKIP ? '○' : '✗';
    const parts = [`${mark} ${s.resolver}`];
    if (s.trust) parts.push(`[${s.trust}]`);
    if (s.detail) parts.push(s.detail);
    if (s.httpStatus) parts.push(`HTTP ${s.httpStatus}`);
    if (s.endpoint) parts.push(s.endpoint);
    if (s.ms) parts.push(`${s.ms}ms`);
    return parts.join(' · ');
  }

  function render() {
    const out = [];
    if (meta.runId) out.push(`Extract run #${meta.runId}`);
    const c = meta.context;
    if (c) {
      out.push(
        `Context · ${c.bvid} · aid ${c.aid} · cid ${c.cid} · P${c.page} · key ${c.contextKey}`
      );
    }
    if (out.length) out.push('');
    for (const s of steps) out.push(renderStep(s));
    if (meta.decision.length) {
      out.push('');
      for (const line of meta.decision) out.push(line);
    }
    return out;
  }

  return { steps, add, setContext, setDecision, render, runId: meta.runId };
}

BS.diagnostics = { createDiagnostics, OK, FAIL, SKIP };

})();
;(function () {
/*
 * Minimal MD5 (RFC 1321) over UTF-8 bytes, used only for WBI signing.
 *
 * Web Crypto intentionally does not provide MD5 and the project avoids
 * runtime dependencies, so this is a compact self-contained implementation.
 * The round constants are hardcoded from the RFC: generating K[i] via
 * Math.sin() is engine-precision-dependent (observed off-by-1-ulp at i=49
 * in V8), which would silently produce wrong digests.
 */

const K = [
  0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
  0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
  0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
  0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
  0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
  0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
  0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
  0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
  0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
  0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
  0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
  0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
  0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
  0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
  0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
  0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391
];

const SHIFTS = [7, 12, 17, 22, 5, 9, 14, 20, 4, 11, 16, 23, 6, 10, 15, 21];

function rotl(x, c) {
  return (x << c) | (x >>> (32 - c));
}

function hexLE(word) {
  let out = '';
  for (let i = 0; i < 4; i++) {
    out += ((word >>> (i * 8)) & 0xff).toString(16).padStart(2, '0');
  }
  return out;
}

function md5Bytes(bytes) {
  const len = bytes.length;
  const paddedLen = ((len + 9 + 63) >> 6) << 6;
  const words = new Int32Array(paddedLen >> 2);
  for (let i = 0; i < len; i++) {
    words[i >> 2] |= bytes[i] << ((i & 3) << 3);
  }
  words[len >> 2] |= 0x80 << ((len & 3) << 3);
  words[words.length - 2] = len << 3;
  words[words.length - 1] = Math.floor(len / 536870912); // bit length >> 32

  let a0 = 0x67452301;
  let b0 = 0xefcdab89 | 0;
  let c0 = 0x98badcfe | 0;
  let d0 = 0x10325476 | 0;

  for (let block = 0; block < words.length; block += 16) {
    let A = a0;
    let B = b0;
    let C = c0;
    let D = d0;
    for (let i = 0; i < 64; i++) {
      let F;
      let g;
      if (i < 16) {
        F = (B & C) | (~B & D);
        g = i;
      } else if (i < 32) {
        F = (D & B) | (~D & C);
        g = (5 * i + 1) & 15;
      } else if (i < 48) {
        F = B ^ C ^ D;
        g = (3 * i + 5) & 15;
      } else {
        F = C ^ (B | ~D);
        g = (7 * i) & 15;
      }
      F = (F + A + K[i] + words[block + g]) | 0;
      A = D;
      D = C;
      C = B;
      B = (B + rotl(F, SHIFTS[(i >> 4) * 4 + (i & 3)])) | 0;
    }
    a0 = (a0 + A) | 0;
    b0 = (b0 + B) | 0;
    c0 = (c0 + C) | 0;
    d0 = (d0 + D) | 0;
  }

  return hexLE(a0) + hexLE(b0) + hexLE(c0) + hexLE(d0);
}

function md5(text) {
  return md5Bytes(new TextEncoder().encode(String(text)));
}

BS.md5 = md5;

})();
;(function () {
/*
 * WBI request signing for signed Bilibili web endpoints.
 *
 * Protocol (docs/PROTOCOL.md §WBI, cross-checked against the community
 * reference and validated by deterministic test vectors):
 *  - GET /x/web-interface/nav exposes data.wbi_img.img_url / sub_url even
 *    when not logged in (code -101); the file names are img_key / sub_key.
 *  - mixin_key = first 32 chars of (img_key + sub_key) permuted through
 *    MIXIN_KEY_ENC_TAB.
 *  - w_rid = md5(sorted, url-encoded query including wts, plus mixin_key).
 *    Values are stripped of !'()* before encoding.
 *
 * Keys rotate server-side, so they are cached briefly (TTL 15 min) and
 * invalidated on signature rejections; the caller retries exactly once.
 * Cookie/login state is carried by the browser itself, never read here.
 */

const NAV_API = 'https://api.bilibili.com/x/web-interface/nav';
const KEY_TTL_MS = 15 * 60 * 1000;

// Fixed permutation from the community protocol reference (verified by
// test vector; see docs/PROTOCOL.md §WBI).
const MIXIN_KEY_ENC_TAB = [
  46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35,
  27, 43, 5, 49, 33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13,
  37, 48, 7, 16, 24, 55, 40, 61, 26, 17, 0, 1, 60, 51, 30, 4,
  22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11, 36, 20, 34, 44, 52
];

function getMixinKey(imgKey, subKey) {
  const raw = String(imgKey) + String(subKey);
  let out = '';
  for (const idx of MIXIN_KEY_ENC_TAB) {
    if (idx < raw.length) out += raw[idx];
  }
  return out.slice(0, 32);
}

function encodeWbiValue(value) {
  return encodeURIComponent(String(value).replace(/[!'()*]/g, ''));
}

function signParams(params, mixinKey, wts) {
  const all = { ...params, wts };
  const query = Object.keys(all)
    .sort()
    .map((key) => `${encodeURIComponent(key)}=${encodeWbiValue(all[key])}`)
    .join('&');
  return { query, wts, wRid: BS.md5(query + mixinKey) };
}

function keyFromUrl(url) {
  const tail = String(url || '').split('?')[0].split('/').pop() || '';
  return tail.replace(/\.[a-z0-9]+$/i, '');
}

const wbiState = { keys: null, fetchedAt: 0, pending: null };

async function fetchKeys(net) {
  // nav returns code -101 when anonymous but still carries wbi_img.
  const data = await net.getJson(NAV_API, { phase: 'wbi-nav' });
  const img = data && data.data && data.data.wbi_img;
  const imgKey = keyFromUrl(img && img.img_url);
  const subKey = keyFromUrl(img && img.sub_url);
  if (!imgKey || !subKey) {
    throw new Error('nav 响应缺少 wbi_img 密钥，无法完成 WBI 签名');
  }
  wbiState.keys = { imgKey, subKey, mixinKey: getMixinKey(imgKey, subKey) };
  wbiState.fetchedAt = Date.now();
  return wbiState.keys;
}

async function getKeys(net) {
  if (wbiState.keys && Date.now() - wbiState.fetchedAt < KEY_TTL_MS) {
    return wbiState.keys;
  }
  if (!wbiState.pending) {
    wbiState.pending = fetchKeys(net).finally(() => {
      wbiState.pending = null;
    });
  }
  return wbiState.pending;
}

function invalidateKeys() {
  wbiState.keys = null;
  wbiState.fetchedAt = 0;
}

// Sign params for one request. `wts` is seconds; injectable via opts for tests.
async function sign(net, params, opts = {}) {
  const keys = await getKeys(net);
  const wts = opts.wts != null ? opts.wts : Math.floor(Date.now() / 1000);
  return { keys, ...signParams(params, keys.mixinKey, wts) };
}

BS.wbi = {
  NAV_API,
  MIXIN_KEY_ENC_TAB,
  getMixinKey,
  signParams,
  sign,
  getKeys,
  invalidateKeys,
  _state: wbiState // exposed for tests (TTL manipulation)
};

})();
;(function () {
/*
 * Minimal protobuf wire-format decoder for /x/v2/subtitle/web/view.
 *
 * Protocol basis (see docs/PROTOCOL.md):
 *   top-level field 1 (length-delimited) = data message
 *   data field 3 (repeated, length-delimited) = subtitle track
 *     track field 1 (varint)            = id
 *     track field 2 (string)            = id_str
 *     track field 3 (string)            = lan        e.g. "ai-zh" / "zh-Hans"
 *     track field 4 (string)            = lan_doc    display name
 *     track field 5 (string)            = subtitle_url
 *     track field 8 (string)            = label (optional)
 *
 * Unknown fields are skipped, never assumed away. The decoder supports
 * wire types 0 (varint), 1 (64-bit), 2 (length-delimited) and 5 (32-bit);
 * wire types 3/4 (deprecated groups) abort parsing. Numbers are decoded
 * with Number (safe here: ids and lengths are far below 2^53).
 */

function readVarint(bytes, offset) {
  let value = 0;
  let shift = 0;
  let pos = offset;
  for (;;) {
    if (pos >= bytes.length) {
      throw new Error(`unterminated varint at ${offset}`);
    }
    const byte = bytes[pos++];
    if (shift < 28) {
      value += (byte & 0x7f) * Math.pow(2, shift);
    } else {
      value = value * Math.pow(2, 7) + (byte & 0x7f);
    }
    if ((byte & 0x80) === 0) return { value, offset: pos };
    shift += 7;
    if (shift > 63) {
      throw new Error(`varint too long at ${offset}`);
    }
  }
}

function decodeMessage(bytes) {
  const fields = [];
  let offset = 0;
  while (offset < bytes.length) {
    const key = readVarint(bytes, offset);
    offset = key.offset;
    const no = key.value / 8 | 0;
    const wt = key.value % 8;
    if (no <= 0) throw new Error(`invalid field number ${no}`);

    if (wt === 0) {
      const value = readVarint(bytes, offset);
      offset = value.offset;
      fields.push({ no, wt, value: value.value });
    } else if (wt === 1) {
      const end = offset + 8;
      if (end > bytes.length) throw new Error('truncated 64-bit field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else if (wt === 2) {
      const len = readVarint(bytes, offset);
      offset = len.offset;
      const end = offset + len.value;
      if (end > bytes.length) throw new Error('truncated length-delimited field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else if (wt === 5) {
      const end = offset + 4;
      if (end > bytes.length) throw new Error('truncated 32-bit field');
      fields.push({ no, wt, bytes: bytes.slice(offset, end) });
      offset = end;
    } else {
      throw new Error(`unsupported wire type ${wt}`);
    }
  }
  return fields;
}

const textDecoder = new TextDecoder('utf-8', { fatal: false });

function getString(fields, no) {
  const field = fields.find((f) => f.no === no && f.wt === 2 && f.bytes);
  return field ? textDecoder.decode(field.bytes) : '';
}

function getVarint(fields, no) {
  const field = fields.find((f) => f.no === no && f.wt === 0);
  return field ? field.value : 0;
}

function toTracks(dataFields) {
  const tracks = [];
  for (const field of dataFields) {
    if (field.no !== 3 || field.wt !== 2 || !field.bytes) continue;
    let inner;
    try {
      inner = decodeMessage(field.bytes);
    } catch (e) {
      BS.warn('protobuf: 跳过损坏的轨道字段', e.message);
      continue;
    }
    const lan = getString(inner, 3);
    const url = getString(inner, 5);
    if (!lan || !url) continue;
    tracks.push({
      id: getVarint(inner, 1) || 0,
      idStr: getString(inner, 2),
      lan,
      lanDoc: getString(inner, 4),
      url,
      label: getString(inner, 8)
    });
  }
  return tracks;
}

function decodeWebViewTracks(buffer) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  const top = decodeMessage(bytes);
  const dataField = top.find((f) => f.no === 1 && f.wt === 2 && f.bytes);
  if (!dataField) {
    return { empty: true, tracks: [] };
  }
  const dataFields = decodeMessage(dataField.bytes);
  const tracks = toTracks(dataFields);
  return { empty: tracks.length === 0, tracks };
}

BS.protobuf = { decodeMessage, decodeWebViewTracks };

})();
;(function () {
/*
 * Network layer. Prefers GM_xmlhttpRequest (bypasses CORS, carries
 * bilibili login cookies automatically for api.bilibili.com) and falls
 * back to page-context fetch with credentials when GM is unavailable.
 *
 * Errors carry structured info (phase / httpStatus / sanitized endpoint)
 * for the diagnostics UI. Cookie values are never read or logged.
 */

function gmRequest(options) {
  return new Promise((resolve, reject) => {
    GM_xmlhttpRequest({
      method: 'GET',
      timeout: 15000,
      headers: {
        Accept: 'application/json,text/plain,*/*',
        Referer: 'https://www.bilibili.com/'
      },
      ...options,
      onload: (r) => resolve(r),
      onerror: () => reject(new Error('network error')),
      ontimeout: () => reject(new Error('timeout'))
    });
  });
}

function pageFetch(url, { responseType } = {}) {
  const consume =
    responseType === 'arraybuffer'
      ? (r) => r.arrayBuffer().then((buffer) => ({
          status: r.status,
          response: buffer,
          contentType: r.headers.get('content-type') || ''
        }))
      : (r) => r.text().then((text) => ({
          status: r.status,
          response: text,
          contentType: r.headers.get('content-type') || ''
        }));

  return fetch(url, {
    method: 'GET',
    credentials: 'include'
  }).then(consume);
}

class NetError extends Error {
  constructor(message, { status, endpoint, phase, body } = {}) {
    super(message);
    this.name = 'NetError';
    this.status = status || 0;
    this.endpoint = endpoint ? BS.sanitizeUrl(endpoint) : '';
    this.phase = phase || '';
    this.body = body ? String(body).slice(0, 200) : '';
  }
}

async function request(url, { phase = '', responseType = 'text', timeout = 15000 } = {}) {
  let status;
  let response;
  let contentType;

  if (typeof GM_xmlhttpRequest === 'function') {
    try {
      const r = await gmRequest({ url, timeout, responseType });
      status = r.status;
      contentType = r.responseHeaders || '';
      response = responseType === 'arraybuffer' ? r.response : r.responseText;
    } catch (e) {
      throw new NetError(`网络错误或超时：${e.message}`, {
        endpoint: url,
        phase
      });
    }
  } else {
    try {
      const r = await pageFetch(url, { responseType });
      status = r.status;
      contentType = r.contentType;
      response = r.response;
    } catch (e) {
      throw new NetError(`网络错误：${e.message}`, {
        endpoint: url,
        phase
      });
    }
  }

  if (status < 200 || status >= 300) {
    let body = '';
    try {
      if (responseType === 'arraybuffer') {
        body = new TextDecoder().decode(new Uint8Array(response)).slice(0, 120);
      } else {
        body = String(response).slice(0, 120);
      }
    } catch (_) { /* ignore */ }
    throw new NetError(`HTTP ${status}`, { status, endpoint: url, phase, body });
  }

  return { status, response, contentType };
}

async function getJson(url, opts = {}) {
  const { response } = await request(url, { ...opts, responseType: 'text' });
  try {
    return JSON.parse(response);
  } catch (e) {
    throw new NetError('返回内容不是 JSON', {
      endpoint: url,
      phase: opts.phase || 'parse-json',
      body: String(response)
    });
  }
}

async function getBinary(url, opts = {}) {
  const { response } = await request(url, { ...opts, responseType: 'arraybuffer' });
  return response instanceof ArrayBuffer ? response : new Uint8Array(response).buffer;
}

BS.net = { request, getJson, getBinary, NetError };

})();
;(function () {
/*
 * SPA navigation detection for www.bilibili.com (no polling).
 *
 * Bilibili routes through history.pushState/replaceState; wrapping them
 * plus popstate/hashchange covers video-to-video jumps, multi-page
 * switches and player rebuilds without touching MutationObserver.
 *
 * The reset callback only fires when the VIDEO IDENTITY changed
 * (bvid/page derived from the URL). Bilibili also issues changeState
 * calls for URL normalization, share params, seek timestamps etc.;
 * resetting on those would needlessly wipe results mid-viewing.
 * Leaving a video page (identity becomes null) still counts as a change.
 */

function videoIdentityKey() {
  if (typeof BS.parseVideoUrl !== 'function') return null;
  const parsed = BS.parseVideoUrl(location.href);
  return parsed ? `${parsed.bvid}:${parsed.page || 1}` : null;
}

function installSpaHooks(onNavigate) {
  const wrapped = [];
  let lastKey = videoIdentityKey();

  function fireIfIdentityChanged() {
    const key = videoIdentityKey();
    if (key === lastKey) return;
    lastKey = key;
    onNavigate();
  }

  function wrapMethod(obj, name) {
    if (!obj || typeof obj[name] !== 'function') return;
    const original = obj[name];
    try {
      obj[name] = function (...args) {
        const result = original.apply(this, args);
        fireIfIdentityChanged();
        return result;
      };
      wrapped.push([obj, name, original]);
    } catch (e) {
      BS.warn('SPA hook 失败', name, e && e.message);
    }
  }

  wrapMethod(window.history, 'pushState');
  wrapMethod(window.history, 'replaceState');

  window.addEventListener('popstate', fireIfIdentityChanged);
  window.addEventListener('hashchange', fireIfIdentityChanged);

  return function uninstall() {
    for (const [obj, name, original] of wrapped) {
      try {
        obj[name] = original;
      } catch (_) { /* ignore */ }
    }
    window.removeEventListener('popstate', fireIfIdentityChanged);
    window.removeEventListener('hashchange', fireIfIdentityChanged);
  };
}

BS.installSpaHooks = installSpaHooks;

})();
;(function () {
/*
 * VideoContext resolver: URL -> { bvid, aid, cid, page, pageCount, title }.
 *
 * Prefers the page-embedded __INITIAL_STATE__ (zero extra requests),
 * falls back to the public view API. In SPA state the embedded data can
 * lag behind navigation, so a bvid mismatch sends us to the API.
 */

const VIEW_API = 'https://api.bilibili.com/x/web-interface/view?bvid=';

function pickPage(pages, wanted) {
  if (!Array.isArray(pages) || pages.length === 0) return null;
  const found = pages.find((x) => Number(x && x.page) === wanted);
  if (found) return found;
  // A missing page number means the embedded data does not describe this
  // URL's part; falling back to pages[0] would silently extract the wrong
  // cid (wrong subtitles). Only the default P1 may use the first page.
  if (!wanted || wanted === 1) return pages[0];
  return null;
}

function contextFromVideoData(videoData, page) {
  if (!videoData || !videoData.bvid) return null;
  const pages = Array.isArray(videoData.pages) ? videoData.pages : [];
  const selected = pickPage(pages, page);
  if (!selected && pages.length > 1) return null;
  const cid = Number((selected && selected.cid) || videoData.cid) || 0;
  if (!cid) return null;
  const base = String(videoData.title || '');
  const multi = pages.length > 1 && selected && selected.part;
  return BS.makeVideoContext({
    bvid: videoData.bvid,
    aid: videoData.aid,
    cid,
    page: Number((selected && selected.page) || page || 1),
    pageCount: pages.length || 1,
    title: multi ? `${base} P${selected.page || page} ${selected.part}` : base
  });
}

async function resolve(env) {
  const parsed = BS.parseVideoUrl(env.href);
  if (!parsed) {
    throw new Error('当前页面不是 B 站视频页（未识别到 BV 号）');
  }

  const inline = contextFromVideoData(
    env.initialState && env.initialState.videoData,
    parsed.page
  );
  if (inline && inline.bvid === parsed.bvid) {
    return inline;
  }

  const data = await env.net.getJson(VIEW_API + encodeURIComponent(parsed.bvid), {
    phase: 'video-context'
  });
  if (!data || data.code !== 0 || !data.data) {
    throw new Error(`视频信息获取失败：code ${data && data.code} ${data && data.message}`);
  }
  const ctx = contextFromVideoData(data.data, parsed.page);
  if (!ctx) throw new Error('视频信息中没有可用的 cid');
  return ctx;
}

BS.resolvers = BS.resolvers || {};
BS.resolvers.videoContext = { name: 'video-context', resolve };

})();
;(function () {
/*
 * Legacy JSON subtitle list - DIAGNOSTIC PROBE ONLY since v1.0.2.
 *
 * GET /x/player/v2?bvid=&cid=  ->  data.subtitle.subtitles[]
 *
 * This endpoint is UNSIGNED. It has been independently reported (risk
 * control degradation) to answer HTTP 200 / code 0 with valid-looking
 * subtitles that actually belong to a DIFFERENT video, so its tracks are
 * stamped UNTRUSTED_LEGACY: the pipeline never loads their bodies, never
 * lets one become the winner and never offers them in the track dropdown.
 * It still runs (concurrently, metadata only) so diagnostics can compare
 * it against the trusted resolvers and the login hint stays accurate.
 */

async function discover(ctx, env) {
  const url =
    'https://api.bilibili.com/x/player/v2' +
    `?bvid=${encodeURIComponent(ctx.bvid)}` +
    `&cid=${encodeURIComponent(ctx.cid)}`;

  const data = await env.net.getJson(url, { phase: 'legacy-json' });
  if (!data || typeof data.code !== 'number') {
    throw new Error('响应缺少 code 字段');
  }
  if (data.code !== 0) {
    throw new Error(`接口返回 code ${data.code}：${data.message || '未知错误'}`);
  }

  const subs = data.data && data.data.subtitle && data.data.subtitle.subtitles;
  if (!Array.isArray(subs) || subs.length === 0) {
    return { tracks: [], note: '字幕列表为空（AI 轨道通常需要登录）' };
  }

  const tracks = subs.map((s, i) =>
    BS.makeTrack({
      id: s.id != null ? s.id : i,
      lan: s.lan,
      lanDoc: s.lan_doc,
      url: s.subtitle_url,
      source: 'legacy',
      aiType: s.ai_type,
      aiStatus: s.ai_status,
      contextKey: ctx.contextKey,
      trust: BS.trust.UNTRUSTED_LEGACY
    })
  );

  return { tracks: tracks.filter((t) => t.url), note: `${tracks.length} 条轨道` };
}

BS.resolvers.legacy = { name: 'legacy-json', discover };

})();
;(function () {
/*
 * Strategy B - New web subtitle metadata API (protobuf).
 *
 * GET /x/v2/subtitle/web/view?oid=<cid>&pid=<aid>&type=1
 *     &context_ext={"video_type":1}&cur_production_type=0&playlist_switch=0
 *
 * Verified anonymously (2026-08): HTTP 200, application/octet-stream,
 * an empty protobuf data message when no tracks are visible (e.g. not
 * logged in). Invalid parameters return a JSON error instead, so the
 * response is sniffed before decoding. See docs/PROTOCOL.md.
 */

function buildUrl(ctx) {
  return (
    'https://api.bilibili.com/x/v2/subtitle/web/view' +
    `?oid=${encodeURIComponent(ctx.cid)}` +
    `&pid=${encodeURIComponent(ctx.aid)}` +
    '&type=1' +
    `&context_ext=${encodeURIComponent('{"video_type":1}')}` +
    '&cur_production_type=0' +
    '&playlist_switch=0'
  );
}

function looksLikeJson(bytes) {
  for (let i = 0; i < Math.min(bytes.length, 16); i++) {
    const b = bytes[i];
    if (b === 0x20 || b === 0x09 || b === 0x0a || b === 0x0d) continue;
    return b === 0x7b || b === 0x5b; // '{' or '['
  }
  return false;
}

async function discover(ctx, env) {
  const url = buildUrl(ctx);
  const buffer = await env.net.getBinary(url, { phase: 'web-view' });
  const bytes = new Uint8Array(buffer);

  if (looksLikeJson(bytes)) {
    let parsed = null;
    try {
      parsed = JSON.parse(new TextDecoder().decode(bytes));
    } catch (_) { /* fallthrough */ }
    if (parsed && parsed.code !== undefined && parsed.code !== 0) {
      throw new Error(`接口返回 code ${parsed.code}：${parsed.message || '未知错误'}`);
    }
    throw new Error('响应为 JSON 但无法识别');
  }

  const { empty, tracks } = BS.protobuf.decodeWebViewTracks(bytes);
  if (empty) {
    return { tracks: [], note: '接口可达但无轨道（未登录或该视频无 AI 字幕）' };
  }

  return {
    tracks: tracks.map((t) =>
      BS.makeTrack({
        id: t.idStr || t.id,
        lan: t.lan,
        lanDoc: t.lanDoc || t.label,
        url: t.url,
        source: 'web-view',
        contextKey: ctx.contextKey,
        trust: BS.trust.CURRENT_VIDEO
      })
    ),
    note: `${tracks.length} 条轨道`
  };
}

BS.resolvers.webView = { name: 'web-view', discover };

})();
;(function () {
/*
 * Strategy A' (primary) - WBI-signed player metadata.
 *
 * GET /x/player/wbi/v2?aid=<aid>&cid=<cid>&wts=<ts>&w_rid=<md5>
 *   -> data.subtitle.subtitles[]  (same shape as the legacy endpoint)
 *
 * Unlike the unsigned /x/player/v2, a correctly signed request is not
 * subject to the risk-control degradation that has been observed to
 * return HTTP 200 with valid-looking subtitles belonging to a DIFFERENT
 * video. Trust level: SIGNED_METADATA.
 *
 * Signature keys come from /x/web-interface/nav via BS.wbi (short-lived
 * cache). On a signature-related rejection (-352 / -403 / HTTP 412) the
 * keys are invalidated and the request is retried exactly once.
 */

const ENDPOINT = 'https://api.bilibili.com/x/player/wbi/v2';
const SIGNATURE_REJECT_CODES = [-352, -403];

function isSignatureNetError(e) {
  return Boolean(e && e.status === 412);
}

async function fetchMetadata(ctx, env) {
  const signed = await BS.wbi.sign(env.net, {
    aid: ctx.aid,
    cid: ctx.cid
  });
  const url = `${ENDPOINT}?${signed.query}&w_rid=${signed.wRid}`;
  const data = await env.net.getJson(url, { phase: 'signed-wbi' });
  return { url, data };
}

// One signature-related failure invalidates the cached keys and is retried
// exactly once; a second failure propagates (no infinite retry loop).
async function fetchWithSignatureRetry(ctx, env) {
  try {
    return await fetchMetadata(ctx, env);
  } catch (e) {
    if (!isSignatureNetError(e)) throw e;
    BS.wbi.invalidateKeys();
    BS.warn('WBI 请求被拦截（HTTP 412），刷新密钥后重试一次');
    return fetchMetadata(ctx, env);
  }
}

async function discover(ctx, env) {
  let { url, data } = await fetchWithSignatureRetry(ctx, env);

  if (data && SIGNATURE_REJECT_CODES.includes(data.code)) {
    BS.wbi.invalidateKeys();
    BS.warn('WBI 签名被拒绝（code ' + data.code + '），刷新密钥后重试一次');
    ({ url, data } = await fetchMetadata(ctx, env));
  }

  if (!data || typeof data.code !== 'number') {
    throw new Error('响应缺少 code 字段');
  }
  if (data.code !== 0) {
    const e = new Error(`接口返回 code ${data.code}：${data.message || '未知错误'}`);
    e.code = data.code;
    throw e;
  }

  const subs = data.data && data.data.subtitle && data.data.subtitle.subtitles;
  if (!Array.isArray(subs) || subs.length === 0) {
    return { tracks: [], note: '字幕列表为空（AI 轨道通常需要登录）' };
  }

  const tracks = subs.map((s, i) =>
    BS.makeTrack({
      id: s.id != null ? s.id : i,
      lan: s.lan,
      lanDoc: s.lan_doc,
      url: s.subtitle_url,
      source: 'signed-wbi',
      aiType: s.ai_type,
      aiStatus: s.ai_status,
      contextKey: ctx.contextKey,
      trust: BS.trust.SIGNED
    })
  );

  return { tracks: tracks.filter((t) => t.url), note: `${tracks.length} 条轨道` };
}

BS.resolvers = BS.resolvers || {};
BS.resolvers.signedWbi = { name: 'signed-wbi', discover };

})();
;(function () {
/*
 * Strategy C (last resort) - Player resource capture.
 *
 * The player's own subtitle requests (aisubtitle.hdslb.com,
 * subtitle.bilibili.com, /bfs/subtitle/) show up as PerformanceResource
 * entries. Entries are captured event-driven via PerformanceObserver
 * (buffered: true), capped, and cleared on SPA navigation.
 *
 * A captured URL is used only when BOTH constraints hold:
 *  1. navigation epoch: the entry was observed during the current video's
 *     session (entries carry the capture epoch; SPA navigation bumps it,
 *     so late observer callbacks for pre-navigation requests are excluded);
 *  2. ownership: the URL embeds the current cid, or (on single-page
 *     videos, where the aid uniquely identifies the part) the current aid.
 * The resource buffer can hold subtitle URLs of *other* videos (playlist
 * prefetch, script re-injection replays), so URLs without both proofs are
 * never probed. This trades a rare fallback (id-less CC URLs) for never
 * showing another video's subtitles.
 */

const SUBTITLE_URL_RE =
  /aisubtitle\.hdslb\.com|subtitle\.bilibili\.com|\/bfs\/subtitle\//;
const MAX_ENTRIES = 50;
const MAX_PROBES = 8;

const capture = {
  entries: [],
  epoch: 0,
  observer: null,

  remember(rawUrl) {
    if (!rawUrl || typeof rawUrl !== 'string') return;
    if (!SUBTITLE_URL_RE.test(rawUrl)) return;
    if (this.entries.some((e) => e.url === rawUrl)) return;
    this.entries.push({ url: rawUrl, time: Date.now(), epoch: this.epoch });
    if (this.entries.length > MAX_ENTRIES) {
      this.entries.splice(0, this.entries.length - MAX_ENTRIES);
    }
  },

  install() {
    if (typeof PerformanceObserver === 'undefined') return;
    try {
      const po = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) {
          this.remember(entry.name);
        }
      });
      po.observe({ type: 'resource', buffered: true });
      this.observer = po;
    } catch (e) {
      BS.warn('PerformanceObserver 不可用', e && e.message);
    }
    if (typeof performance !== 'undefined' && performance.getEntriesByType) {
      try {
        for (const entry of performance.getEntriesByType('resource')) {
          this.remember(entry.name);
        }
      } catch (_) { /* ignore */ }
    }
  },

  list() {
    return this.entries.slice().sort((a, b) => b.time - a.time);
  },

  reset() {
    this.entries = [];
    this.epoch++;
  }
};

function matchesNumber(url, number) {
  if (!number) return false;
  return new RegExp(`(^|[^0-9])${number}([^0-9]|$)`).test(String(url));
}

/*
 * Ownership evidence: the URL embeds the current cid, or it embeds the
 * aid on a single-page video. Multi-page videos share one aid across all
 * parts, so an aid-only match could be another part's subtitles.
 */
function ownsUrl(url, ctx) {
  if (!url || !ctx) return false;
  if (matchesNumber(url, ctx.cid)) return true;
  const singlePage = !ctx.pageCount || Number(ctx.pageCount) <= 1;
  return singlePage && matchesNumber(url, ctx.aid);
}

async function probe(ctx, env, item) {
  const data = await env.net.getJson(item.url, { phase: 'player-resource' });
  const cues = BS.parseSubtitleJson(data);
  if (!cues.length) {
    throw new Error('字幕内容为空');
  }
  const track = BS.makeTrack({
    id: 'captured',
    lan: /ai_subtitle|aisubtitle/.test(item.url) ? 'ai-zh' : '',
    lanDoc: '播放器已加载字幕',
    url: item.url,
    source: 'player-resource',
    contextKey: ctx.contextKey,
    trust: BS.trust.CURRENT_PLAYER
  });
  track.cues = cues;
  return track;
}

async function discover(ctx, env) {
  const all = env.getEntries ? env.getEntries() : capture.list();
  // Constraint 1 of 2: only entries observed in the current navigation
  // epoch (this video's session) are considered at all.
  const currentEpoch = capture.epoch;
  const urlMatches = all.filter((e) => SUBTITLE_URL_RE.test(e.url));
  const staleEpochCount = urlMatches.filter((e) => e.epoch !== currentEpoch).length;
  const candidates = urlMatches.filter((e) => e.epoch === currentEpoch);

  if (!candidates.length) {
    if (staleEpochCount > 0) {
      return {
        tracks: [],
        note: `捕获到 ${staleEpochCount} 条字幕 URL，但属于上一次导航会话（与当前视频不匹配），已跳过`
      };
    }
    return {
      tracks: [],
      note: '尚无播放器字幕请求（可在播放器中打开 CC 字幕后重试）',
      soft: true
    };
  }

  const pool = candidates.filter((e) => ownsUrl(e.url, ctx));
  if (!pool.length) {
    return {
      tracks: [],
      note: `捕获到 ${candidates.length} 条字幕 URL，但与当前视频不匹配（已跳过，避免串用其他视频的字幕）`
    };
  }

  const tracks = [];
  for (const item of pool.slice(0, MAX_PROBES)) {
    try {
      tracks.push(await probe(ctx, env, item));
    } catch (e) {
      BS.log('捕获 URL 无效，跳过', BS.sanitizeUrl(item.url), e && e.message);
    }
  }

  if (!tracks.length) {
    return { tracks: [], note: '捕获的 URL 均无法读取（可能已过期）' };
  }
  return { tracks, note: `${tracks.length} 条可读取` };
}

BS.resolvers = BS.resolvers || {};
BS.resolvers.playerResource = { name: 'player-resource', discover, ownsUrl };
BS.resourceCapture = capture;

})();
;(function () {
/*
 * Subtitle resolver pipeline.
 *
 * Production chain, in order (first trusted success wins):
 *   1. signed-wbi      /x/player/wbi/v2      (WBI-signed metadata)
 *   2. web-view        /x/v2/subtitle/web/view (protobuf, aid+cid in query)
 *   3. player-resource captured player requests (epoch + ownership proof)
 *
 * The unsigned /x/player/v2 (legacy-json) is NOT part of the chain: it has
 * been reported to return HTTP 200 with valid-looking subtitles belonging
 * to a DIFFERENT video (risk-control degradation). It runs concurrently as
 * a metadata-only diagnostic probe; its tracks are stamped UNTRUSTED_LEGACY
 * and can never become the winner, be loaded, or enter the track dropdown.
 *
 * Every track/result is bound to the video context via contextKey
 * (bvid:cid) and a trust level; only winnable trust + matching contextKey
 * passes the authorization helper. Signed subtitle URLs are never cached:
 * a 403/404 body fetch triggers one extra discovery round with fresh
 * metadata. Every attempt is recorded as a diagnostics step with a runId.
 *
 * env = { net, href, initialState, getEntries, onUpdate, onContext }
 * (all injectable so the whole pipeline runs under node:test with mocks)
 */

const EXPIRY_STATUS = [403, 404];

const TRUST_BY_RESOLVER = {
  'signed-wbi': () => BS.trust.SIGNED,
  'web-view': () => BS.trust.CURRENT_VIDEO,
  'player-resource': () => BS.trust.CURRENT_PLAYER,
  legacy: () => BS.trust.UNTRUSTED_LEGACY
};

function trustOfSource(name) {
  const fn = TRUST_BY_RESOLVER[name];
  return fn ? fn() : '';
}

let runCounter = 0;

function isExpiryError(err) {
  return err && EXPIRY_STATUS.includes(err.status);
}

function now() {
  return Date.now();
}

/*
 * Authorization: a track may be loaded, displayed or selected only when
 * its trust level is winnable AND it is provably bound to the current
 * video context. UNTRUSTED_LEGACY tracks fail this check by design.
 */
function isSelectableTrack(track, ctx) {
  return Boolean(
    track &&
      track.url &&
      ctx &&
      BS.isWinnableTrust(track.trust) &&
      track.contextKey === ctx.contextKey
  );
}

async function loadBody(track, env, tried) {
  if (Array.isArray(track.cues) && track.cues.length) {
    return track.cues;
  }
  if (!track.url || tried.has(track.url)) {
    throw new Error('跳过（已尝试过或无地址）');
  }
  tried.add(track.url);

  const data = await env.net.getJson(track.url, { phase: 'body' });
  const cues = BS.parseSubtitleJson(data);
  if (!cues.length) throw new Error('字幕内容为空');
  return cues;
}

async function runStrategy(resolver, ctx, env, diag, tried) {
  const started = now();

  let result;
  try {
    result = await resolver.discover(ctx, env);
  } catch (e) {
    diag.add({
      resolver: resolver.name,
      status: BS.diagnostics.FAIL,
      detail: e.message,
      httpStatus: e.status,
      endpoint: e.endpoint,
      trust: trustOfSource(resolver.name),
      ms: now() - started
    });
    BS.warn(resolver.name, '失败', e);
    return { tracks: [], retryable: isExpiryError(e) };
  }

  const okDetail = result.note || `${result.tracks.length} 条轨道`;
  diag.add({
    resolver: resolver.name,
    status: result.soft ? BS.diagnostics.SKIP : BS.diagnostics.OK,
    detail: okDetail,
    trust: trustOfSource(resolver.name),
    ms: now() - started
  });

  if (!result.tracks.length) {
    return { tracks: [], retryable: false };
  }

  const candidates = BS.sortTracks(
    result.tracks.filter((t) => !tried.has(t.url))
  );

  let sawExpiry = false;
  for (const track of candidates) {
    // Defense in depth: chain resolvers stamp winnable trust, but never
    // rely on that alone.
    if (!isSelectableTrack(track, ctx)) {
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.SKIP,
        detail: `轨道未通过信任/归属校验（trust ${track.trust || '缺失'}），跳过`
      });
      continue;
    }
    if (Array.isArray(track.cues) && track.cues.length) {
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.OK,
        detail: `${track.cues.length} 条（播放器捕获验证）`,
        ms: 0
      });
      return { tracks: result.tracks, doc: { track, cues: track.cues } };
    }
    const bodyStarted = now();
    try {
      const cues = await loadBody(track, env, tried);
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.OK,
        detail: `${track.lanDoc || track.lan} · ${cues.length} 条`,
        ms: now() - bodyStarted
      });
      return { tracks: result.tracks, doc: { track, cues } };
    } catch (e) {
      diag.add({
        resolver: `${resolver.name}#fetch`,
        status: BS.diagnostics.FAIL,
        detail: e.message,
        httpStatus: e.status,
        endpoint: e.endpoint,
        ms: now() - bodyStarted
      });
      if (isExpiryError(e)) {
        sawExpiry = true;
        BS.warn('字幕地址已过期，将重新获取 metadata', BS.sanitizeUrl(track.url));
      }
    }
  }

  return { tracks: result.tracks, retryable: sawExpiry };
}

/*
 * Diagnostic probe: unsigned legacy metadata, never committed.
 * Metadata only — bodies of UNTRUSTED_LEGACY tracks are never fetched.
 */
async function probeLegacy(ctx, env, diag) {
  const started = now();
  try {
    const result = await BS.resolvers.legacy.discover(ctx, env);
    const count = result.tracks.length;
    diag.add({
      resolver: 'legacy-json(诊断)',
      status: BS.diagnostics.OK,
      detail: `${result.note || `${count} 条轨道`}（未采信：未签名接口不作为结果来源）`,
      trust: BS.trust.UNTRUSTED_LEGACY,
      ms: now() - started
    });
    return { ok: true, tracks: result.tracks };
  } catch (e) {
    diag.add({
      resolver: 'legacy-json(诊断)',
      status: BS.diagnostics.FAIL,
      detail: e.message,
      httpStatus: e.status,
      endpoint: e.endpoint,
      trust: BS.trust.UNTRUSTED_LEGACY,
      ms: now() - started
    });
    return { ok: false, error: e };
  }
}

function buildHints(diagSteps, probe) {
  const okNote = (name) =>
    diagSteps.some(
      (s) =>
        s.resolver === name &&
        s.status === BS.diagnostics.OK &&
        s.detail &&
        !/条轨道/.test(s.detail)
    );

  const notes = [];
  if (probe && probe.ok && probe.tracks.length) {
    notes.push(
      '未签名的 /x/player/v2 此刻返回了轨道，但该接口无法证明字幕归属（曾观测到返回其他视频的字幕），已按策略忽略。'
    );
  }
  if (okNote('signed-wbi') && okNote('web-view')) {
    notes.push('两个可信接口都返回空轨道：AI 字幕通常需要登录 B 站后才能获取。');
  }
  notes.push(
    '兜底提示：在播放器中打开「字幕 / CC」并选择 AI 字幕，让播放器实际加载一次，再点「重新提取」。'
  );
  return notes;
}

async function extract(env) {
  const runId = ++runCounter;
  const runTag = `[run:${runId}]`;
  const diag = BS.diagnostics.createDiagnostics({ runId });
  const tried = new Set();
  env.onUpdate && env.onUpdate(`正在识别视频…（run #${runId}）`);

  let ctx;
  try {
    ctx = await BS.resolvers.videoContext.resolve(env);
  } catch (e) {
    diag.add({
      resolver: 'video-context',
      status: BS.diagnostics.FAIL,
      detail: e.message
    });
    return { ok: false, runId, error: e, tracks: [], diag };
  }
  diag.add({
    resolver: 'video-context',
    status: BS.diagnostics.OK,
    detail: `${ctx.bvid} · aid ${ctx.aid} · cid ${ctx.cid} · P${ctx.page} · key ${ctx.contextKey}`
  });
  diag.setContext(ctx);
  env.onContext && env.onContext(ctx);
  BS.log(
    runTag,
    'context',
    `${ctx.bvid} · aid ${ctx.aid} · cid ${ctx.cid} · P${ctx.page}`,
    `key ${ctx.contextKey}`
  );

  // Untrusted legacy probe runs concurrently with the trusted chain so it
  // never slows the happy path down.
  const legacyProbeP = probeLegacy(ctx, env, diag);

  const strategies = [
    BS.resolvers.signedWbi,
    BS.resolvers.webView,
    BS.resolvers.playerResource
  ];

  let merged = [];
  let doc = null;
  let winnerName = '';
  let retryable = false;

  for (const strategy of strategies) {
    env.onUpdate && env.onUpdate(`正在尝试：${strategy.name}（run #${runId}）`);
    const r = await runStrategy(strategy, ctx, env, diag, tried);
    merged = BS.mergeTracks([merged, r.tracks]);
    if (r.doc) {
      doc = r.doc;
      winnerName = strategy.name;
      break;
    }
    if (r.retryable) retryable = true;
  }

  if (!doc && retryable) {
    env.onUpdate && env.onUpdate(`字幕地址已过期，正在重新获取…（run #${runId}）`);
    for (const strategy of [BS.resolvers.signedWbi, BS.resolvers.webView]) {
      const r = await runStrategy(strategy, ctx, env, diag, tried);
      merged = BS.mergeTracks([merged, r.tracks]);
      if (r.doc) {
        doc = r.doc;
        winnerName = strategy.name;
        break;
      }
    }
  }

  const probe = await legacyProbeP;

  // Belt and suspenders: only tracks with winnable trust AND a matching
  // contextKey ever reach the selectable track list.
  merged = merged.filter((t) => isSelectableTrack(t, ctx));

  if (doc && probe.ok && probe.tracks.length) {
    // Diagnostic-only cross-check, no extra requests: if the trusted
    // result and the untrusted probe disagree on languages, surface it.
    const trustedLans = new Set(merged.map((t) => t.lan));
    const legacyLans = new Set(probe.tracks.map((t) => t.lan));
    const overlap = [...legacyLans].some((l) => trustedLans.has(l));
    if (!overlap) {
      diag.add({
        resolver: 'cross-check',
        status: BS.diagnostics.SKIP,
        detail: 'legacy 探针与可信结果的轨道语言集合不一致（legacy 未采信，仅提示）'
      });
      BS.warn(runTag, 'legacy 探针与可信结果不一致（未采信，仅提示）');
    }
  }

  if (!doc) {
    const hints = buildHints(diag.steps, probe);
    const error = new Error(
      [`未能提取到字幕（run #${runId}）`, ...hints].filter(Boolean).join('\n')
    );
    error.hints = hints;
    diag.setDecision([`Decision · FAIL（run #${runId}）`]);
    return { ok: false, runId, error, ctx, tracks: merged, diag };
  }

  diag.setDecision([
    `Winner · ${winnerName} · trust ${doc.track.trust} · key ${doc.track.contextKey}`,
    `Ignored · legacy-json（${BS.trust.UNTRUSTED_LEGACY}：未签名接口不作为结果来源）`
  ]);
  BS.log(
    runTag,
    'winner',
    winnerName,
    doc.track.lanDoc || doc.track.lan,
    `${doc.cues.length} 条`,
    `trust ${doc.track.trust}`
  );

  return {
    ok: true,
    runId,
    ctx,
    track: doc.track,
    cues: doc.cues,
    tracks: merged,
    diag
  };
}

async function loadTrackBody(track, env) {
  const started = now();
  const cues = await env.net.getJson(track.url, { phase: 'body' }).then((d) => {
    const parsed = BS.parseSubtitleJson(d);
    if (!parsed.length) throw new Error('字幕内容为空');
    return parsed;
  });
  BS.log('轨道加载完成', track.lanDoc || track.lan, `${cues.length} 条`, `${now() - started}ms`);
  return cues;
}

BS.pipeline = { extract, loadTrackBody, isSelectableTrack };

})();
;(function () {
/*
 * Minimal UI: a "字幕" pill at the bottom-right and a small popover with
 * track list, export actions, preview and collapsed diagnostics.
 *
 * Dynamic content is set via textContent only (no HTML interpolation of
 * video titles or subtitle text). No settings page, no themes.
 */

const STYLE = `
#bs-pill {
  position: fixed; right: 20px; bottom: 84px; z-index: 2147483644;
  border: 0; border-radius: 999px; background: #fb7299; color: #fff;
  padding: 8px 14px; font-size: 13px; font-weight: 600; cursor: pointer;
  box-shadow: 0 4px 14px rgba(0,0,0,.25); font-family: inherit;
}
#bs-panel {
  position: fixed; right: 20px; bottom: 130px; z-index: 2147483645;
  width: min(400px, calc(100vw - 40px)); max-height: min(70vh, 560px);
  overflow: auto; background: #fff; color: #18191c; border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0,0,0,.3); font-size: 13px; line-height: 1.6;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif;
}
#bs-head {
  display: flex; align-items: center; gap: 8px; padding: 10px 12px;
  border-bottom: 1px solid #eee;
}
#bs-title { flex: 1; min-width: 0; font-weight: 700;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
#bs-close { border: 0; background: transparent; font-size: 18px;
  cursor: pointer; color: #888; line-height: 1; }
#bs-status { padding: 6px 12px; color: #666; font-size: 12px; }
#bs-msg { margin: 0 12px 8px; padding: 8px 10px; border-radius: 8px;
  background: #fdeef0; color: #b2303f; white-space: pre-wrap; }
#bs-controls { display: flex; flex-wrap: wrap; gap: 6px; padding: 0 12px 8px; }
#bs-count { padding: 0 12px 6px; color: #444; }
#bs-actions { display: flex; flex-wrap: wrap; gap: 6px; padding: 0 12px 8px; }
#bs-panel button, #bs-panel select {
  border: 1px solid #ddd; border-radius: 7px; background: #fff;
  padding: 5px 9px; cursor: pointer; color: #18191c; font-size: 12px; max-width: 100%;
}
#bs-panel button:hover { border-color: #fb7299; color: #fb7299; }
#bs-preview { margin: 0 12px 8px; padding: 8px 10px; background: #f7f8fa;
  border-radius: 8px; max-height: 180px; overflow: auto; white-space: pre-wrap;
  font: 12px/1.6 ui-monospace, Menlo, Consolas, monospace; }
#bs-diag-box { margin: 0 12px 10px; }
#bs-diag-box summary { cursor: pointer; color: #888; font-size: 12px; }
#bs-diag { margin: 6px 0 0; padding: 8px 10px; background: #f7f8fa;
  border-radius: 8px; white-space: pre-wrap; font: 11px/1.7 ui-monospace, Menlo, Consolas, monospace; }
`;

const TEMPLATE = `
<div id="bs-panel" hidden>
  <div id="bs-head">
    <span id="bs-title">bili-subtitle</span>
    <button id="bs-close" title="关闭">×</button>
  </div>
  <div id="bs-status">就绪</div>
  <div id="bs-msg" hidden></div>
  <div id="bs-controls">
    <button id="bs-extract">提取字幕</button>
    <select id="bs-tracks" hidden></select>
  </div>
  <div id="bs-count" hidden></div>
  <div id="bs-actions" hidden>
    <button data-act="copy">复制文本</button>
    <button data-act="copy-ts">带时间轴</button>
    <button data-act="txt">TXT</button>
    <button data-act="srt">SRT</button>
    <button data-act="json">JSON</button>
  </div>
  <pre id="bs-preview" hidden></pre>
  <details id="bs-diag-box" hidden>
    <summary>获取路径</summary>
    <pre id="bs-diag"></pre>
  </details>
</div>
`;

function createPanel(handlers) {
  const root = document.createElement('div');
  root.id = 'bs-root';

  const style = document.createElement('style');
  style.textContent = STYLE;
  root.appendChild(style);

  const pill = document.createElement('button');
  pill.id = 'bs-pill';
  pill.textContent = '字幕';
  root.appendChild(pill);

  root.insertAdjacentHTML('beforeend', TEMPLATE);
  document.body.appendChild(root);

  const $ = (id) => root.querySelector(`#${id}`);
  const panel = $('bs-panel');
  const title = $('bs-title');
  const status = $('bs-status');
  const msg = $('bs-msg');
  const extractBtn = $('bs-extract');
  const tracksSel = $('bs-tracks');
  const count = $('bs-count');
  const actions = $('bs-actions');
  const preview = $('bs-preview');
  const diagBox = $('bs-diag-box');
  const diagPre = $('bs-diag');

  let trackKeyOf = () => '';

  function open() {
    panel.hidden = false;
  }

  function close() {
    panel.hidden = true;
  }

  pill.addEventListener('click', () => {
    if (panel.hidden) {
      open();
      if (handlers.onOpen) handlers.onOpen();
    } else {
      close();
    }
  });

  $('bs-close').addEventListener('click', close);
  extractBtn.addEventListener('click', () => handlers.onExtract());

  tracksSel.addEventListener('change', () => {
    handlers.onTrackChange(tracksSel.value);
  });

  actions.addEventListener('click', (e) => {
    const act = e.target && e.target.dataset && e.target.dataset.act;
    if (act) handlers.onExport(act);
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') close();
  });

  const api = {
    open,
    close,

    setTitle(text) {
      title.textContent = text || 'bili-subtitle';
    },

    setStatus(text) {
      status.textContent = text || '';
    },

    setMessage(text) {
      if (text) {
        msg.textContent = text;
        msg.hidden = false;
      } else {
        msg.hidden = true;
      }
    },

    setBusy(busy) {
      extractBtn.disabled = !!busy;
      extractBtn.textContent = busy ? '提取中…' : '提取字幕';
    },

    setTracks(tracks, selectedKey) {
      tracksSel.innerHTML = '';
      trackKeyOf = (t) => `${t.source}|${t.lan}|${t.url}`;
      for (const t of tracks) {
        const opt = document.createElement('option');
        opt.value = trackKeyOf(t);
        const label = t.lanDoc || t.lan || '字幕';
        opt.textContent =
          t.source === 'player-resource'
            ? `${label}（播放器捕获）`
            : label;
        if (trackKeyOf(t) === selectedKey) opt.selected = true;
        tracksSel.appendChild(opt);
      }
      tracksSel.hidden = tracks.length < 2;
    },

    findTrack(tracks, key) {
      return tracks.find((t) => `${t.source}|${t.lan}|${t.url}` === key) || null;
    },

    setCues(cues, track) {
      count.textContent = `${cues.length} 条 · ${track.lanDoc || track.lan || '字幕'} · 来源 ${track.source}`;
      count.hidden = false;
      actions.hidden = false;
      const head = cues
        .slice(0, 15)
        .map((c) => BS.exporters.fmtClock(c.from) + '  ' + c.content)
        .join('\n');
      preview.textContent =
        cues.length > 15 ? head + '\n…' : head;
      preview.hidden = false;
      msg.hidden = true;
    },

    setDiag(lines) {
      if (!lines || !lines.length) return;
      diagPre.textContent = lines.join('\n');
      diagBox.hidden = false;
    },

    clearResult() {
      count.hidden = true;
      actions.hidden = true;
      preview.hidden = true;
      msg.hidden = true;
      tracksSel.innerHTML = '';
      tracksSel.hidden = true;
      diagPre.textContent = '';
      diagBox.hidden = true;
    }
  };

  return api;
}

BS.ui = { createPanel };

})();
;(function () {
/*
 * Entry point: state, UI wiring, export actions, SPA reset.
 */

function createAppState() {
  // gen: monotonic token. Every user action that starts an async flow
  // (extract, track load) or invalidates one (SPA navigation) bumps it;
  // a flow whose gen is no longer current must not touch state or panel.
  return { ctx: null, tracks: [], track: null, cues: [], gen: 0 };
}

function makeEnv(state, panel, isStale) {
  return {
    net: BS.net,
    href: location.href,
    initialState: typeof window.__INITIAL_STATE__ !== 'undefined'
      ? window.__INITIAL_STATE__
      : null,
    getEntries: () => BS.resourceCapture.list(),
    onUpdate: (text) => {
      if (!isStale || !isStale()) panel.setStatus(text);
    },
    onContext: (ctx) => {
      if (!isStale || !isStale()) panel.setTitle(ctx.title || ctx.bvid);
    }
  };
}

function copyText(text) {
  if (typeof GM_setClipboard === 'function') {
    GM_setClipboard(text, 'text');
    return Promise.resolve();
  }
  return navigator.clipboard.writeText(text);
}

function downloadText(text, filename, type = 'text/plain;charset=utf-8') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.documentElement.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}

function baseName(state) {
  return BS.exporters.safeName(
    (state.ctx && state.ctx.title) || state.ctx.bvid || 'bilibili-subtitle'
  );
}

/*
 * Current video identity straight from the URL. Used as a commit-time
 * guard: even if the generation token is still current (e.g. a missed
 * SPA hook), a result computed for a different bvid/page must not land.
 */
function currentVideoIdentity() {
  const parsed = BS.parseVideoUrl(location.href);
  return parsed ? { bvid: parsed.bvid, page: parsed.page || 1 } : null;
}

function identityMatches(ctx) {
  const fresh = currentVideoIdentity();
  return Boolean(fresh && ctx && fresh.bvid === ctx.bvid && fresh.page === ctx.page);
}

function applyResult(state, panel, result) {
  state.tracks = result.tracks || [];
  panel.setDiag(result.diag.render());

  if (!result.ok) {
    state.track = null;
    state.cues = [];
    panel.setMessage(result.error.message);
    panel.setStatus('提取失败，详见「获取路径」');
    BS.errorLog('提取失败');
    for (const line of result.diag.render()) BS.errorLog(line);
    return;
  }

  state.track = result.track;
  state.cues = result.cues;
  panel.setMessage('');
  panel.setTracks(state.tracks, `${result.track.source}|${result.track.lan}|${result.track.url}`);
  panel.setCues(result.cues, result.track);
  panel.setStatus('提取成功');
  BS.log(
    '提取成功',
    result.track.lanDoc || result.track.lan,
    `${result.cues.length} 条`,
    `来源 ${result.track.source}`
  );
}

async function onExtract(state, panel) {
  if (state.extracting) return;
  const gen = ++state.gen;
  state.extracting = true;
  panel.setBusy(true);
  panel.clearResult();
  panel.setMessage('');

  const stale = () => gen !== state.gen;
  try {
    const result = await BS.pipeline.extract(makeEnv(state, panel, stale));
    if (stale()) {
      BS.log(`[run:${result && result.runId}]`, '提取结果已过期（视频已切换），丢弃');
      return;
    }
    // Commit needs BOTH conditions: current generation AND the page still
    // being the video this result belongs to.
    if (!identityMatches(result.ctx)) {
      BS.log(`[run:${result.runId}]`, '结果与当前页面视频不一致，丢弃');
      panel.setStatus('页面视频已变化，请重新提取');
      return;
    }
    state.ctx = result.ctx || state.ctx;
    applyResult(state, panel, result);
    if (result.runId) panel.setStatus(`提取成功（run #${result.runId}）`);
  } catch (e) {
    if (stale()) {
      BS.log('提取错误已过期（视频已切换），丢弃');
      return;
    }
    panel.setMessage(e && e.message ? e.message : String(e));
    panel.setStatus('提取失败');
    BS.errorLog('未预期的错误', e);
  } finally {
    // A superseded run must not clear the busy flag of the run that owns
    // the current gen (the SPA hook already reset the flag when it bumped gen).
    if (!stale()) {
      state.extracting = false;
      panel.setBusy(false);
    }
  }
}

async function onTrackChange(state, panel, key) {
  const track = panel.findTrack(state.tracks, key);
  if (!track) return;
  // Fail closed: only a track provably bound to the current video context
  // may be loaded.
  if (!BS.pipeline.isSelectableTrack(track, state.ctx)) {
    panel.setStatus('该轨道与当前视频不匹配，已拒绝');
    panel.setMessage('轨道归属校验失败，请点「提取字幕」重新获取。');
    BS.warn('track change 拒绝：trust/contextKey 校验未通过', BS.sanitizeUrl(track.url));
    return;
  }
  const gen = ++state.gen;
  const stale = () => gen !== state.gen;
  panel.setStatus(`正在读取：${track.lanDoc || track.lan}…`);
  try {
    const cues = await BS.pipeline.loadTrackBody(track, makeEnv(state, panel, stale));
    if (stale()) {
      BS.log('轨道结果已过期，丢弃');
      return;
    }
    if (!identityMatches(state.ctx)) {
      BS.log('轨道结果与当前页面视频不一致，丢弃');
      panel.setStatus('页面视频已变化，请重新提取');
      return;
    }
    state.track = track;
    state.cues = cues;
    panel.setCues(cues, track);
    panel.setStatus('提取成功');
  } catch (e) {
    if (stale()) return;
    panel.setStatus('轨道读取失败');
    panel.setMessage(
      (e && e.status === 403) || (e && e.status === 404)
        ? '该字幕地址已过期，请点「提取字幕」重新获取。'
        : (e && e.message) || String(e)
    );
    BS.warn('轨道读取失败', BS.sanitizeUrl(track.url), e && e.message);
  }
}

function onExport(state, panel, act) {
  if (!state.cues || !state.cues.length || !state.track) {
    panel.setStatus('当前没有字幕，请先提取');
    return;
  }
  const { cues, track, ctx } = state;
  const base = baseName(state);
  const done = (what) => panel.setStatus(`${what}完成`);

  switch (act) {
    case 'copy':
      copyText(BS.exporters.toPlainText(cues)).then(
        () => done('复制'),
        () => panel.setStatus('复制失败')
      );
      break;
    case 'copy-ts':
      copyText(BS.exporters.toTimestampedText(cues)).then(
        () => done('复制'),
        () => panel.setStatus('复制失败')
      );
      break;
    case 'txt':
      downloadText(BS.exporters.toTimestampedText(cues), `${base}.txt`);
      done('TXT 下载');
      break;
    case 'srt':
      downloadText(
        BS.exporters.toSrt(cues),
        `${base}.srt`,
        'application/x-subrip;charset=utf-8'
      );
      done('SRT 下载');
      break;
    case 'json':
      downloadText(
        BS.exporters.toJson(ctx, track, cues),
        `${base}.json`,
        'application/json;charset=utf-8'
      );
      done('JSON 下载');
      break;
  }
}

function boot() {
  if (!document.body) return false;

  const state = createAppState();
  const panel = BS.ui.createPanel({
    onOpen: () => {
      if (!state.cues.length && !state.extracting) onExtract(state, panel);
    },
    onExtract: () => onExtract(state, panel),
    onTrackChange: (key) => onTrackChange(state, panel, key),
    onExport: (act) => onExport(state, panel, act)
  });

  BS.resourceCapture.install();

  BS.installSpaHooks(() => {
    // Invalidate any in-flight extract / track load for the previous
    // video; their results must never land on the new video's panel.
    state.gen++;
    BS.resourceCapture.reset();
    state.extracting = false;
    panel.setBusy(false);
    state.ctx = null;
    state.tracks = [];
    state.track = null;
    state.cues = [];
    panel.clearResult();
    panel.setTitle('bili-subtitle');
    panel.setStatus('已切换视频，点击「提取字幕」');
    BS.log('SPA 导航：状态已重置');
  });

  BS.log(`v${BS.VERSION} 已加载`);
  return true;
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot);
} else {
  boot();
}

})();
})();
