#!/usr/bin/env node
/*
 * Zero-dependency build: concatenate src files (each a plain script
 * sharing the BS namespace) into a single installable userscript.
 *
 *   node scripts/build.mjs            -> writes bili-subtitle.user.js
 *   node scripts/build.mjs --check    -> exits 1 if output is stale
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { packSources } from './pack.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const FILES = [
  'src/00-namespace.js',
  'src/core/log.js',
  'src/core/model.js',
  'src/core/video-url.js',
  'src/core/cues.js',
  'src/core/exporters.js',
  'src/core/diagnostics.js',
  'src/core/md5.js',
  'src/core/wbi.js',
  'src/core/protobuf.js',
  'src/core/net.js',
  'src/core/spa.js',
  'src/resolvers/video-context.js',
  'src/resolvers/legacy.js',
  'src/resolvers/web-view.js',
  'src/resolvers/signed-wbi.js',
  'src/resolvers/player-resource.js',
  'src/resolvers/index.js',
  'src/ui/panel.js',
  'src/main.js'
];

const version = readFileSync(path.join(root, FILES[0]), 'utf8').match(
  /BS\.VERSION\s*=\s*'([^']+)'/
)[1];

const header = `// ==UserScript==
// @name         bili-subtitle
// @namespace    https://github.com/ymt200120
// @version      ${version}
// @description  弹性提取 Bilibili CC / AI 字幕：自动尝试多条获取路径，失败时给出精确诊断。零配置、不读取 Cookie。
// @description:en  Resilient Bilibili CC & AI subtitle extraction with automatic fallback strategies and precise diagnostics. Zero-config, never touches cookies.
// @author       ymt200120
// @homepageURL  https://github.com/ymt200120/bili-subtitle
// @supportURL   https://github.com/ymt200120/bili-subtitle/issues
// @downloadURL  https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @updateURL    https://raw.githubusercontent.com/ymt200120/bili-subtitle/main/bili-subtitle.user.js
// @match        https://www.bilibili.com/video/*
// @match        https://www.bilibili.com/list/*
// @noframes
// @grant        GM_xmlhttpRequest
// @grant        GM_setClipboard
// @connect      api.bilibili.com
// @connect      aisubtitle.hdslb.com
// @connect      subtitle.bilibili.com
// @connect      hdslb.com
// @run-at       document-end
// @license      MIT
// ==/UserScript==

/*
 * bili-subtitle v${version} - https://github.com/ymt200120/bili-subtitle
 * This file is generated by \`npm run build\`; edit files under src/ instead.
 */
`;

const body = packSources(
  FILES.map((file) => ({ file, code: readFileSync(path.join(root, file), 'utf8') }))
);

const output = `${header}(function () {\n'use strict';\n\n${body}\n})();\n`;

const outFile = path.join(root, 'bili-subtitle.user.js');
const check = process.argv.includes('--check');

if (check) {
  let current = '';
  try {
    current = readFileSync(outFile, 'utf8');
  } catch (_) { /* missing */ }
  if (current !== output) {
    console.error('bili-subtitle.user.js is stale; run: npm run build');
    process.exit(1);
  }
  console.log('build check ok');
} else {
  writeFileSync(outFile, output);
  const kb = (Buffer.byteLength(output) / 1024).toFixed(1);
  console.log(`wrote bili-subtitle.user.js v${version} (${kb} KB)`);
}
